### ISSUE TITLE
Librenms not consistently reporting rebooted or offline servers

### ISSUE THREAD

**Issue by carinity** [librenms/librenms#1017]
We have been using Librenms for the last 2-3 weeks after using observium for some years  Currently we are finding that it is not reporting rebooted or offline servers consistently . We rebooted about 10 servers this morning and only 2 were rebooted in the overview as rebooted. Last week we had an outage of remote servers and almost none were reported in overview. However when just one or is offline we do see the outage notifcation.

**Comment by f0o** [comment]
Hi @carinity,

Are you using the default-set of rules? If not, can you paste me your rule + delay&count values please?

The default rule for up/down will only alert if a device is down for longer than 5 minutes, if your devices reboot quick enough it's treated as a 'bump' and it's discarded.
You can change this behavior by adjusting the 'delay' value of the rule downwards.

**Comment by paulgear** [comment]
@f0o, this is just for front screen notifications, not alerts

**Comment by f0o** [comment]
ah ok, relabeling

**Comment by laf** [comment]
we see the same actually just never looked into it. It's the way some devices report uptime back + roll over counters.

**Comment by f0o** [comment]
Removing my assignment because I dont use the hostboxes anywhere and I cant reproduce it.
Maybe @laf can have a deeper look at it?

**Comment by laf** [comment]
Happy to on this one.

**Comment by laf** [comment]
So this is actually not the same as what I initially thought.

@carinity Can you confirm some details please:

What is $config['uptime_warning'] set to
What is $config['front_page_down_box_limit'] set to

They may not be in config.php, if not then that's fine they should then be using the defaults.

The boxes on the front page will show devices that have rebooted and have a sysUptime of > 0 but < than $config['uptime_warning'] which is currently configured to be just less than 24 hours.

For devices down, this relies on the database to be updated which is only done at poller time, so if a device is polled then rebooted and comes back before the next poll cycle then it should show it as rebooted rather than down.

It's also worth noting that only 10 devices will be shown in the boxes as we limit the mysql query to 10 results, you can change this by setting $config['front_page_down_box_limit'] to something other than 10.

**Comment by paulgear** [comment]
I think the limit 10 is the most likely cause; @carinity, please try changing $config['front_page_down_box_limit'] and see if that fixes the issue.

**Comment by Lonecrowe** [comment]
Mine is working perfect.  I thought this was based on uptime?
