### ISSUE TITLE
Adtran/Ubiquoss/Commscope C9500 OLT New Device Support

### ISSUE THREAD

**Issue by jdtinsley88** [librenms/librenms#10601]
[NEW-OS-SUPPORT-COMMANDS.txt](https://github.com/librenms/librenms/files/3606498/NEW-OS-SUPPORT-COMMANDS.txt)
Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Attached is the output of the following commands -

./discovery.php -h HOSTNAME -d | ./pbin.sh
./poller.php -h HOSTNAME -r -f -d | ./pbin.sh
snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh

Also attached is the 2 different sets of MIBs from Ubiquoss and also the Ubiquoss Logo

Detail -
Adtran has the North American Distribution Rights to Ubiquoss.  Adtran acquired Commscope, which Commscope is the North American branding/version of Ubiquoss.

OS Name is Ubiquoss

C9500 OLT is EPON

Hopefully, a new OS template can be created.

If possible, please try to get the following -

Tpon Interface Optical Light Readings

PON ONU bridging-entries -

 1/4-1.2     0024.4508.3bf9
 1/4-1.3     0003.e637.4006
 1/4-1.4     0024.4508.3bf8

PON ONU Light Readings -

  PON NETWORK ONU DDM FOR 10G-OLT(1/4) INFORMATION
================================================================================
 INDEX       RX POWER   TX POWER        VCC       BIAS   TEMPERATURE
--------------------------------------------------------------------------------
 1/4-1           0.17       1.83       3.26       9.75      31.89
================================================================================

  -- ONU 1/4-1 DDM Information --
 RX Laser Power                 :                  0.15 dBm

 TX Laser Power                 :                  1.88 dBm
 Laser VCC                      :                 3.260 volt
 Laser Bias                     :                 9.950 mAmp
 Laser temperature              :                32.562 Celsius

![ubiquoss](https://user-images.githubusercontent.com/45700408/64800635-878e6e00-d54c-11e9-9eaf-54dadc08fe97.png)
[Ubiquoss-mibs.zip](https://github.com/librenms/librenms/files/3606421/Ubiquoss-mibs.zip)
[9500_mib_r320c.zip](https://github.com/librenms/librenms/files/3606423/9500_mib_r320c.zip)

**Comment by jerrydao** [comment]
I tried to create New OS for this and got this error:
sysDescr: U9516 DPoE Software Version DPOE.R351B, <<HW_REV: 1.0; VENDOR: Ubiquoss; BOOTR: 1.1.1>>
sysObjectID: .1.3.6.1.4.1.7800.1.206

Enter the description for this OS, i.e Cisco IOS: U9516 DPoE Software Version DPOE.R351B
Enter the logo to use, this can be the name of an existing one (i.e: cisco) or the url to retrieve one: ubiquoss
Base discovery file created,ctrl+c to exit now otherwise please enter the MIB name including path (url is also fine) for us to check for sensors: /opt/librenms/mibs/ubiquoss
MIB search path: /opt/librenms/mibs:/opt/librenms/mibs/ubiquoss
Cannot find module (ubiquoss): At line 0 in (none)
Unable to find a matching object identifier for ".*Table$"
Failed to create new discovery file /opt/librenms/includes/definitions/discovery/DPoE.yaml

**Comment by PipoCanaja** [comment]
Hi @jdtinsley88 @jerrydao 
PR 10828 is adding basic support for these devices. Let us know how it goes with your real devices. 
Bye

**Comment by jdtinsley88** [comment]
> Hi @jdtinsley88 @jerrydao
> PR 10828 is adding basic support for these devices. Let us know how it goes with your real devices.
> Bye

When will this be available to try out?
