### ISSUE TITLE
SNMP unreachable suddenly

### ISSUE THREAD

**Issue by tylerapplebaum** [librenms/librenms#1119]
Hello. Last night at 12:15AM SNMP suddenly became "unreachable" to all of my network devices. No network changes were made. I woke up to ~12k e-mails.

SNMP is running:

root@librenms:/opt/librenms# netstat -nplu
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
udp        0      0 127.0.0.1:161           0.0.0.0:*                           1151/snmpd      
udp        0      0 0.0.0.0:68              0.0.0.0:*                           739/dhclient3   

Here's the sanitized output from ./poller.php -h <device> -d

root@librenms:/opt/librenms# ./poller.php -h rtr-sa59 -d
PHP Deprecated:  Comments starting with '#' are deprecated in /etc/php5/cli/conf.d/mcrypt.ini on line 1 in Unknown on line 0
        LibreNMS 2014.master Poller

DEBUG!
Starting polling run:

SQL[SELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE 'rtr-sa59' ORDER BY `device_id` ASC]
SQL[SELECT * FROM `devices` WHERE `device_id` = '82']
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '82'] rtr-sa59 82 ios (cisco)
DEBUG: SNMP Auth options =  -v2c -c <sanitized>
/usr/bin/snmpget -v2c -c <sanitized> -Oqv -m SNMPv2-MIB -M /opt/librenms/mibs udp:rtr-sa59:161 sysObjectID.0
add_mibdir: strings scanned in from /opt/librenms/mibs/.index are too large.  count = 104
 Cannot find module (SNMPv2-MIB): At line 0 in (none)
sysObjectID.0: Unknown Object Identifier (Sub-id not found: (top) -> sysObjectID)

DEBUG: SNMP Auth options =  -v2c -c <sanitized>
/usr/bin/snmpget -v2c -c <sanitized> -Oqv -m SNMPv2-MIB -M /opt/librenms/mibs udp:rtr-sa59:161 SNMPv2-SMI::enterprises.39165.1.1.0
add_mibdir: strings scanned in from /opt/librenms/mibs/.index are too large.  count = 104
 Cannot find module (SNMPv2-MIB): At line 0 in (none)
Cannot find module (SNMPv2-SMI): At line 0 in (none)
SNMPv2-SMI::enterprises.39165.1.1.0: Unknown Object Identifier

SNMP Unreachable
SQL[SELECT * FROM device_groups]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='82' && (devices.hostname LIKE "rtr-sa"  ) LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='82' && (devices.hostname LIKE "san" ) LIMIT 1]
SQL[SELECT DISTINCT(alert_schedule.schedule_id) FROM alert_schedule LEFT JOIN alert_schedule_items ON alert_schedule.schedule_id=alert_schedule_items.schedule_id WHERE ( alert_schedule_items.target = '82' ) && NOW() BETWEEN alert_schedule.start AND alert_schedule.end LIMIT 1]
SQL[SELECT * FROM device_groups]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='82' && (devices.hostname LIKE "rtr-sa"  ) LIMIT 1]
SQL[SELECT DISTINCT(devices.device_id) FROM devices WHERE device_id='82' && (devices.hostname LIKE "san" ) LIMIT 1]
SQL[SELECT alert_rules.* FROM alert_rules LEFT JOIN alert_map ON alert_rules.id=alert_map.rule WHERE alert_rules.disabled = 0 && ( (alert_rules.device_id = -1 || alert_rules.device_id = '82' ) || alert_map.target = '82'  )]  #1:
SQL[SELECT state FROM alerts WHERE rule_id = '1' && device_id = '82' ORDER BY id DESC LIMIT 1]
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'devices' && COLUMN_NAME = 'device_id']
SQL[SELECT * FROM devices WHERE (devices.device_id = '82') && (devices.status != "1"  &&  devices.disabled = "0"  &&  devices.ignore = "0")]  NOCHG  #2:
SQL[SELECT state FROM alerts WHERE rule_id = '2' && device_id = '82' ORDER BY id DESC LIMIT 1]
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'devices' && COLUMN_NAME = 'device_id']
SQL[SELECT * FROM devices WHERE (devices.device_id = '82') && (devices.uptime < "300"  &&  devices.disabled = "0"  &&  devices.ignore = "0")]  NOCHG  #3:
SQL[SELECT state FROM alerts WHERE rule_id = '3' && device_id = '82' ORDER BY id DESC LIMIT 1]
SQL[SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_NAME = 'bgpPeers' && COLUMN_NAME = 'device_id']
SQL[SELECT * FROM bgpPeers WHERE (bgpPeers.device_id = '82') && (bgpPeers.bgpPeerState != "established")]  NOCHG

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('poll','rtr-sa59','1432395829.072','0.148','1','librenms\n')] ./poller.php rtr-sa59 2015-05-23 08:43:49 - 1 devices polled in 0.148 secs

MySQL: Cell[5/0s] Row[12/0.01s] Rows[2/0s] Column[0/0s] Update[0/0s] Insert[1/0s] Delete[0/0s]

**Comment by f0o** [comment]
remove  `/opt/librenms/mibs/.index`
we're working on identifying the source of this rare issue.

**Comment by tylerapplebaum** [comment]
Much better!

**Comment by laf** [comment]
We've got another issue open with this #1274

**Comment by scottscreations** [comment]
This just happened to me, same time as the original poster described. We are on the latest, i check that. I did some nmap scans and it was librenms as soon as i removed that .index and ran the the poller everything was back up.

**Comment by scottscreations** [comment]
I want to point out that this just happened again after the last git update to my system and took everything down. I had to 'rm /opt/librenms/mibs/.index' to make it poll again.

**Comment by laf** [comment]
What version are you on and when did you last update, I'm certain this was resolved.

**Comment by scottscreations** [comment]
Version	d526a16 - Tue Jan 24 2017 17:25:40 GMT-0700
DB Schema	#157
Web Server	Apache/2.2.22 (Ubuntu)
PHP	5.3.10-1ubuntu3.25
MySQL	5.5.54-0ubuntu0.12.04.1
RRDtool	1.4.7

**Comment by laf** [comment]
When did you last update before then?

We really don't have any info to debug this further in general though :(

**Comment by scottscreations** [comment]
We can rule it as a fluke and see what happens in the future. I changed my cron job to run the daily.sh an hour after work instead of midnight. I can't tell you what version it was on. I did run the validate a few times to see if it would fix it. here is a dump of daily.log

Returned: 0
Updating SQL-Schema
-- Updating database schema
154 -> 155 ... done (0 errors).
-- Done
Returned: 0
Updating submodules

Returned: 0
Cleaning up DB
Refreshing alert rules queries
Eventlog cleared for entries over 30 days
Device performance times cleared for entries over 7 days
Returned: 0
Fetching notifications
[ Wed, 18 Jan 2017 00:15:17 -0700 ] http://www.librenms.org/notifications.rss (8)
[ Wed, 18 Jan 2017 00:15:18 -0700 ] misc/notifications.rss (13)
[ Wed, 18 Jan 2017 00:15:18 -0700 ] Updating DB  Done
Returned: 0
Updating to latest codebase

Returned: 0
Updated from 84dca9435e39e8875bf03b09cfe1deaa59fa91ff to 6829293f1b55eda19473d23fe90f49828a655ddd

Returned: 0
Updating SQL-Schema

Returned: 0
Updating submodules

Returned: 0
Cleaning up DB
Refreshing alert rules queries
Eventlog cleared for entries over 30 days
Authlog cleared for entries over 30 days
Device performance times cleared for entries over 7 days
Alert log data cleared for entries over 365 days
Returned: 0
Fetching notifications
[ Thu, 19 Jan 2017 00:15:17 -0700 ] http://www.librenms.org/notifications.rss (8)
[ Thu, 19 Jan 2017 00:15:18 -0700 ] misc/notifications.rss (13)
[ Thu, 19 Jan 2017 00:15:18 -0700 ] Updating DB  Done
Returned: 0
Updating to latest codebase

Returned: 0
Updated from 6829293f1b55eda19473d23fe90f49828a655ddd to 81bde0b8da6c798245a7916ac6e2096a9c4ab1cc

Returned: 0
Updating SQL-Schema
-- Updating database schema
155 -> 156 ... done (0 errors).
-- Done
Returned: 0
Updating submodules

Returned: 0
Cleaning up DB
Refreshing alert rules queries
Eventlog cleared for entries over 30 days
Device performance times cleared for entries over 7 days
Returned: 0
Fetching notifications
[ Fri, 20 Jan 2017 00:15:18 -0700 ] http://www.librenms.org/notifications.rss (8)
[ Fri, 20 Jan 2017 00:15:18 -0700 ] misc/notifications.rss (13)
[ Fri, 20 Jan 2017 00:15:18 -0700 ] Updating DB  Done
Returned: 0
Updating to latest codebase

Returned: 0
Updated from 81bde0b8da6c798245a7916ac6e2096a9c4ab1cc to 9c13afe8ad031d60b257cea3883c68c08523f941

Returned: 0
Updating SQL-Schema

Returned: 0
Updating submodules

Returned: 0
Cleaning up DB
Refreshing alert rules queries
Eventlog cleared for entries over 30 days
Authlog cleared for entries over 30 days
Device performance times cleared for entries over 7 days
Alert log data cleared for entries over 365 days
Returned: 0
Fetching notifications
[ Sat, 21 Jan 2017 00:15:18 -0700 ] http://www.librenms.org/notifications.rss (8)
[ Sat, 21 Jan 2017 00:15:19 -0700 ] misc/notifications.rss (13)
[ Sat, 21 Jan 2017 00:15:19 -0700 ] Updating DB  Done
Returned: 0
Updating to latest codebase

Returned: 0
Updated from 9c13afe8ad031d60b257cea3883c68c08523f941 to b644c5cc73bc8fdaa2923bef65c9c79abdc039f5

Returned: 0
Updating SQL-Schema

Returned: 0
Updating submodules

Returned: 0
Cleaning up DB
Refreshing alert rules queries
Eventlog cleared for entries over 30 days
Device performance times cleared for entries over 7 days
Alert log data cleared for entries over 365 days
Returned: 0
Fetching notifications
[ Sun, 22 Jan 2017 00:15:17 -0700 ] http://www.librenms.org/notifications.rss (8)
[ Sun, 22 Jan 2017 00:15:18 -0700 ] misc/notifications.rss (13)
[ Sun, 22 Jan 2017 00:15:18 -0700 ] Updating DB  Done
Returned: 0
Updating to latest codebase

Returned: 0
Updated from b644c5cc73bc8fdaa2923bef65c9c79abdc039f5 to 8f17025803d655a7a3e24edfcfe0be57e809b560

Returned: 0
Updating SQL-Schema
-- Updating database schema
156 -> 157 ... done (0 errors).
-- Done
Returned: 0
Updating submodules

Returned: 0
Cleaning up DB
Refreshing alert rules queries
Eventlog cleared for entries over 30 days
Device performance times cleared for entries over 7 days
Returned: 0
Fetching notifications
[ Mon, 23 Jan 2017 00:15:16 -0700 ] http://www.librenms.org/notifications.rss (8)
[ Mon, 23 Jan 2017 00:15:16 -0700 ] misc/notifications.rss (13)
[ Mon, 23 Jan 2017 00:15:16 -0700 ] Updating DB  Done
Returned: 0
Updating to latest codebase

Returned: 0
Updated from 8f17025803d655a7a3e24edfcfe0be57e809b560 to d970764674dc870b4be444fe4c7ed4a8ee12214b

Returned: 0
Updating SQL-Schema

Returned: 0
Updating submodules

Returned: 0
Cleaning up DB
Refreshing alert rules queries
Eventlog cleared for entries over 30 days
Authlog cleared for entries over 30 days
Device performance times cleared for entries over 7 days
Returned: 0
Fetching notifications
[ Tue, 24 Jan 2017 00:15:17 -0700 ] http://www.librenms.org/notifications.rss (8)
[ Tue, 24 Jan 2017 00:15:17 -0700 ] misc/notifications.rss (13)
[ Tue, 24 Jan 2017 00:15:17 -0700 ] Updating DB  Done
Returned: 0
Updating to latest codebase

Returned: 0
Updated from d970764674dc870b4be444fe4c7ed4a8ee12214b to d526a16042418d27f3404de28d98118bc67bef57

Returned: 0
Updating SQL-Schema

Returned: 0
Updating submodules

Returned: 0
Cleaning up DB
Refreshing alert rules queries
Eventlog cleared for entries over 30 days
Device performance times cleared for entries over 7 days
Returned: 0
Fetching notifications
[ Wed, 25 Jan 2017 00:15:16 -0700 ] http://www.librenms.org/notifications.rss (8)
[ Wed, 25 Jan 2017 00:15:16 -0700 ] misc/notifications.rss (13)
[ Wed, 25 Jan 2017 00:15:16 -0700 ] Updating DB  Done
Returned: 0
Updating to latest codebase

Returned: 0
Updating SQL-Schema

Returned: 0
Updating submodules

Returned: 0
Cleaning up DB
Refreshing alert rules queries
Eventlog cleared for entries over 30 days
Device performance times cleared for entries over 7 days
Returned: 0
Fetching notifications
[ Wed, 25 Jan 2017 09:14:42 -0700 ] http://www.librenms.org/notifications.rss (8)
[ Wed, 25 Jan 2017 09:14:43 -0700 ] misc/notifications.rss (13)
[ Wed, 25 Jan 2017 09:14:43 -0700 ] Updating DB  Done
Returned: 0

**Comment by laf** [comment]
Thanks for the log. It shows you have been on daily updates so it's not due to an old version or anything.

At present you're the only one who's reporting this :(

**Comment by arrmo** [comment]
Wondering if this is what I'm seeing in #5363?

It sure seemed like I was losing connectivity ... but good now it seems (fingers crossed).

**Comment by laf** [comment]
Different issue, this is a hard down on all devices so you'd know about it.

**Comment by arrmo** [comment]
OK, thanks!
