### ISSUE TITLE
Updated OS for Cisco FirePOWER devices

### ISSUE THREAD

**Issue by Brickbr1** [librenms/librenms#11205]
Building on [#10046](https://github.com/librenms/librenms/pull/10046)

Looking for the following sysObjectID to be added
.1.3.6.1.4.1.9.1.2406 # { ciscoProducts 2407 } -- Cisco FirePOWER 2130 Security Appliance, 1U with embedded security
.1.3.6.1.4.1.9.1.2405 # { ciscoProducts 2407 } -- Cisco FirePOWER 2120 Security Appliance, 1U with embedded security
.1.3.6.1.4.1.9.1.2404 # { ciscoProducts 2407 } -- Cisco FirePOWER 2110 Security Appliance, 1U with embedded security
.1.3.6.1.4.1.9.1.2319 # { ciscoProducts 2319 } -- Cisco FirePOWER Virtual Appliance

please add:    
 - { graph: device_mempool, text: 'Memory' }
 - { graph: device_processor, text: 'Processor' }

**Comment by PipoCanaja** [comment]
Hi @Brickbr1 
Why don't you add those directly ? The steps are pretty simple :
- Change the definition of the OS to add the text in this description
- Provide the test data for one or two devices
This issue is anyway incomplete (you did not provide all the data required for an issue, and removed all the text that should not be removed :) ) so this is your best chance to see this happening so far.

**Comment by PipoCanaja** [comment]
Done ! Thanx @Brickbr1. Closing this now.
