### ISSUE TITLE
HDD SMART data

### ISSUE THREAD

**Issue by stpq** [librenms/librenms#1161]
from linux box (custom OIDs?)

**Comment by Lonecrowe** [comment]
I've always wanted this too.  It would take a lot of scripting to be placed on each linux box though and then translated into data back to libre to be graphed.   There are a lot of codes to monitor as well.  We'd have to pick and choose.  

Especially some of the SSD codes would be extremely important for some people as it is a good gauge when the write performance starts to degrade.

**Comment by f0o** [comment]
How about check_mk with munin-plugins?
(https://github.com/munin-monitoring/munin/blob/master/plugins/node.d/smart_)

**Comment by Lonecrowe** [comment]
Nagios has a check_smartmon plugin as well but I've never used it and not sure how well it works.

**Comment by f0o** [comment]
@Lonecrowe nagios-checks are not for remote hosts tho ;)

**Comment by Lonecrowe** [comment]
No but the service check system uses nagios plugins right?  Or does it only use the plugins on the server.   So libre does not use nrpe or anything like that?

**Comment by f0o** [comment]
nope, all nagios-checks are running from the server that hosts librenms

**Comment by f0o** [comment]
Closing this one, feel free to reopen if you like

**Comment by jquagga** [comment]
So I started down this road before deciding for my use case I didn't need it.  But I figured I'd write down what I found.  

Using the nagios plugin's doesn't really work.  Partially because librenms doesn't support the ide_smart plugin (it doesn't accept the -H tag) but mostly because the plugin has to run as root to query the smart status and librenms doesn't traditionally run as root.  

So I moved on to adding a snmp extend script which when run with sudo permissions would provide the device and whether a device PASSED or FAILED smart testing / health reports.  It's essentially this:

```bash
#!/usr/bin/env dash

DEVICES="/dev/sda /dev/sdb /dev/sdc"

for value in $DEVICES
do
    echo $value
    if [ -z $(sudo smartctl -q errorsonly -H -l selftest /dev/sda) ];
    then
        echo PASSED
    else
        echo FAILED
    fi
done
```

This could then be parsed into a Device, Status pair and then in theory mapped to a state health sensor.  By the time I had gotten this far, I just configured smartd to send me alerts on a failing drive so it seemed like a lot to try and integrate this into librenms.  But I will leave this in case anyone else comes down this road one day.

**Comment by jquagga** [comment]
Oh minor typo in that script. /dev/sda in the smartctl command should be $value.

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-hdd-smart-data/741

**Comment by laf** [comment]
Anyone who is interested in this please test https://github.com/librenms/librenms/pull/6181
