### ISSUE TITLE
net-snmp: unusable `.index` in `/opt/librenms/mibs`

### ISSUE THREAD

**Issue by carinity** [librenms/librenms#1274]
at exactly midnight last night librenms started reporting all devices as down . 

I understand that every now & then net-snmp decides to create a .index file in the /opt/librenms/mibs directory that it can't use.  Deleting it solves the problem.

**Comment by f0o** [comment]
Yes this `.index` issue is very annoying, I've run into it only 2 times (yet?)

**Comment by SaaldjorMike** [comment]
Do we know if it is due to the exact contents of the .index file or merely the existence of it?

**Comment by paulgear** [comment]
Just the existence; deleting it fixes the issue.  @f0o, I wonder if we need to just delete the file during the daily update.  @laf - thoughts?

**Comment by f0o** [comment]
The file doesnt just popup at midnight, I've experienced it both at random times :/

It would be good to know what actually causes this. I'm not even sure if the existence is really the problem, snmpget complains about the list in the .index being too long.

Maybe we should start thinking in splitting the mibs into dirs. Who knows, an alphabetical or vendor hierarchy with a lot of `-M` params might as well fix it because each dir would contain it's own `.index` which is shorter in length and thus may not trigger the issue...

**Comment by laf** [comment]
@f0o @paulgear we do need to split the mibs into dirs, that's the reason for the .index. I believe the reason is that the MIBs directory is scanned - at what stage I really don't know - but as we have so many MIBs then it can't finish the scan and leaves the .index file.

I expect it's specific to a particular disco / poller run which not everyone uses - I've never come across this issue at all so far.

**Comment by laf** [comment]
Re-opening to track the longer term fix (mib dir split)

**Comment by laf** [comment]
Some debug output:

```bash

/opt/librenms/mibs# diff .index index.jmb
112c112
< CISCO-HSRP-MIB CISCO-HSRP-MIB
---
> CIMIB
227a228
> CISCO-ENTITY-ASSETY-MIB
334c335
< CISCOSB-rndApplications CISCOSB-rndApplications
---
> CISCOSB-rndApplications
437d437
< MIB-Dell-OME MIB-Dell-OME
1103a1104,1105
> UPS-MIB UPS-MIB
> MPLN-MIB ENTERASYS-ACTIVATION-MIB
```

**Comment by SaaldjorMike** [comment]
Just stumbled upon this issue. Poller debug shows:
```
add_mibdir: strings scanned in from /opt/librenms/mibs/.index are too large.  count = 658
 MIB search path: /opt/librenms/mibs
Cannot find module (SNMPv2-MIB): At line 0 in (none)
sysObjectID.0: Unknown Object Identifier (Sub-id not found: (top) -> sysObjectID)
```
As stated previously, removing the .index file "resolves" the issue.

**Comment by scottscreations** [comment]
This just happened to me, same time as the original poster described. We are on the latest, i check that. I did some nmap scans and it was librenms as soon as i removed that .index and ran the the poller everything was back up.

**Comment by laf** [comment]
Update again and see if it's fixed

**Comment by scottscreations** [comment]
updated, we'll see. Thanks!

**Comment by florianbeer** [comment]
I had the exact same issue after last nights git update: 
`add_mibdir: strings scanned in from /opt/librenms/mibs/.index are too large.  count = 443`

Sent all my devices to "snmp offline" (and a flurry of alert emails ensued). After deleting `/opt/librenms/mibs/.index` all is well again.
