### ISSUE TITLE
Service alerts cause "Rule created, no errors found" history entries

### ISSUE THREAD

**Issue by nightcore500** [librenms/librenms#13424]
### The problem

Since 23.10 I observe many "Rules created, no faults found" entries in the alert history although nobody has created new rules. These messages always occur as soon as a service is on warning or critical or returns to normal. Our services are simple icmp checks. Other alerts do not cause these entries.

![Screenshot 2021-10-25 111322](https://user-images.githubusercontent.com/25873532/138671705-e8f2779b-0b3d-4134-b4b7-1d64c3591f53.png)
![Screenshot 2021-10-25 111339](https://user-images.githubusercontent.com/25873532/138671708-ce746f06-28aa-47bd-9293-356354e72c82.png)

### Output of ./validate.php

```txt
$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 21.10.0-47-g5536c8bdc
DB Schema | 2021_10_20_224207_increase_length_of_attrib_type_column (224)
PHP       | 7.4.20
Python    | 3.7.3
MySQL     | 10.5.11-MariaDB-1-log
RRDTool   | 1.7.1
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 2.1.9
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

**Comment by bugsse** [comment]
I have a similar issue. The alert log is filled with "Rule created, no faults found" entries not associated to any device.
We first noticed it when our SQL slowed down due to over 3 million entries in the alert_logs table.
It seems to be related to the alert rules, because if I disable all the alert rules the log entries stop.

====================================
Component | Version
--------- | -------
LibreNMS  | 21.11.0-43-g364fa540c
DB Schema | 2021_11_17_105321_device_add_display_field (227)
PHP       | 8.0.11
Python    | 3.8.10
MySQL     | 10.3.31-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | 5.8
====================================

[OK]    Composer Version: 2.1.12
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct


![librenms](https://user-images.githubusercontent.com/46709434/143553772-71d734ce-a13f-4f86-9584-6d1ac75b76d0.png)

**Comment by nightcore500** [comment]
Does this also happen to you as soon as a service causes an alert?
How exactly did you configure your "Devices up/down" rule? I noticed that only alarm rules are affected which use either the macros "macros.device_up", "macros.device_down", "macros.device" or just "devices.last_ping_timetaken". Rules without this are not in my logs.

**Comment by bugsse** [comment]
It uses the "macros.device_down".
I will have to look into if other rules also generates does logs, but my first guess is that they do not.

**Comment by murrant** [comment]
`Rule created, no faults found` seems to be a message in the webui when there are no alert details.  Not sure where to look further than that...

**Comment by bugsse** [comment]
> `Rule created, no faults found` seems to be a message in the webui when there are no alert details. Not sure where to look further than that...

We have used LibreNMS for several years and never seen one until i few months ago, and now we generate tens of thousands each day. In a matter of weeks it took down our SQL server so there is no way this can be by design.

**Comment by nightcore500** [comment]
I can reproduce this problem on my test environment as follows:
- create an ICMP service (I use the parameters "-w 500.0ms,40% -c 700.0ms,60% -n 5 -t 2" but it won't matter)
- create some alert rules. For example:

1. macros.device_down = 1 AND devices.status_reason = "icmp"
2. macros.port_down = 1
3. ports.ifSpeed < ports.ifSpeed_prev AND macros.port_up = 1 AND ports.ifSpeed != 0
4. (ports.ifOutErrors_rate >= 1 OR ports.ifInErrors_rate >= 1) AND macros.port_up = 1

and for the service check itself:
services.service_status = 2 AND macros.device_up = 1

- If you now make sure that the service changes to critical (for example by changing the IP of the ICMP check to an IP that cannot be reached) the other alert rules appear in the alert log (Rule created, no faults found) shortly before the actual service alert appears. This also happens after the service switches back to OK. First the other alerts appear in the alert log as "Rule created, no faults found" and shortly after that the actual service alert.

**Comment by bugsse** [comment]
We have found a workaround, it doesn't really solve the problem but it removes the symptoms and might give someone with more insight a clue.
Instead of using the builtin "All devices" (leaving the "Match devices..." field empty") group when creating an Alert rule, we created a dynamic group called "Everything" with "devices.hostname REGEXP ".*""
This still allows the alert rules to hit on all devices, but it does not give us the "Rule created, no faults found" entries.

My very uneducated guess without even looking at the source is that somehow, somewhere we have some kind of corrupt device entries in the database that generates those errors when the alert rules hit them. I've tried some simple SQL queries to return all devices with empty fields but that did not turn up anything suspicious.

**Comment by murrant** [comment]
@bugsse how about a service associated with a deleted device?

**Comment by nightcore500** [comment]
Small update:
I just noticed that the "Rule created, no faults found" messages appear at every polling as long as one of the services is on critical. So the messages do not only appear when changing from OK to Critical and vice versa but appear at every polling while the service is on Critical.

**Comment by merentitis** [comment]
I also experience the same problem since updating from 21.10.2 to 21.11.0 and later docker images. Every 5 minutes I get these "Rule created, no faults found" messages.

**Comment by k0079898** [comment]
I had the same problem too.
Every time the services had a status change, the NULL device alert appears.
My first NULL device alert appeared on 2021/10/22. After I commented out those changes in #13348, the NULL device alert no longer appears.

**Comment by murrant** [comment]
@k0079898 Can you add `Log::critical("Service alert check device_id: $service->device_id");` and check librenms.log to see if there are any "null" device_ids?

**Comment by k0079898** [comment]
@murrant I added the code and deliberately changed one service status, the `librenms.log` file didn't show the corresponding device's id.
Seems this empty device input triggers every rule inside `AlertRules.php` to update the SQL with `device_id = 0, state = 0, details=NULL` log.

![螢幕擷取畫面 2022-01-10 145038](https://user-images.githubusercontent.com/25053973/148727603-94e5d922-e625-4d8c-b2c6-f50a2f49c0ba.png)

![螢幕擷取畫面 2022-01-10 151138](https://user-images.githubusercontent.com/25053973/148729344-bb877389-c601-49ec-93c1-b0ccd75eb7b5.png)

**Comment by k0079898** [comment]
A little update:
I find out you will get the device_id correctly when you use `$service['device_id']` instead of `$service->device_id`.

![螢幕擷取畫面 2022-01-10 163757](https://user-images.githubusercontent.com/25053973/148737708-5102db39-49c3-4129-8032-06f3146c7d44.png)

**Comment by murrant** [comment]
@k0079898 yes, that is what I was working towards.  If it does fix it up (it should), please send a pull request with that change.
