### ISSUE TITLE
Widget Value incorrect for Huawei OLT 

### ISSUE THREAD

**Issue by liqinsg** [librenms/librenms#13639]
### The problem

Server widget shows 0 value for MPU boards but there have value in Health/Memory

![image](https://user-images.githubusercontent.com/32053924/147739014-57c62736-884d-43c2-97af-38963559b131.png)

![image](https://user-images.githubusercontent.com/32053924/147738983-d5447f32-1741-466a-9faa-63c355b7132b.png)

Huawei OLT Huawei SmartAX EA5800V100R019C20B056 

### Output of ./validate.php

```txt
librenms@esplnms:~$ ./validate.php 
====================================
Component | Version
--------- | -------
LibreNMS  | 21.12.0
DB Schema | 2021_11_29_165436_improve_ports_search_index (229)
PHP       | 7.4.3
Python    | 3.8.10
MySQL     | 10.3.32-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | 5.8
====================================

[OK]    Composer Version: 2.2.1
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

**Comment by aztec102** [comment]
Hello @liqinsg.
For example, I will give my charts from almost the same piece of hardware. The division of the graphics into slots is correct, is it the same for you?
![изображение](https://user-images.githubusercontent.com/3264305/148229587-eea7b3f4-17b8-46b6-9a6e-8998999a5fbe.png)
![изображение](https://user-images.githubusercontent.com/3264305/148229795-aca1ac8a-85ec-4ebc-8b65-8796cdcf2132.png)

**Comment by liqinsg** [comment]
The chart is ok. The value in dashboard widget incorrect

**Comment by PipoCanaja** [comment]
Hi @liqinsg 
In fact, the chart is displaying percents instead of the actual value (probably because the absolute value is not provided by MIB). But looking at the units, the percents are displayed as "Bytes" -> 100% is drawn and stored as 100 bytes. Which is indeed 0 MBytes ...

In order to solve this, you'll need to find a way to get the actual memory value and not a "percent" value as it is now.
