### ISSUE TITLE
Check Point - BGP peers not showing

### ISSUE THREAD

**Issue by Prolicide** [librenms/librenms#13652]
### The problem

Hello,
We have BGP configured on an equipment but we are having an issue where libreNMS is not detecting BGP peering and states for firewalls, namely:
Hardware: Check Point 15400
Operating System: Check Point GAiA R80.40

How to resolve this issue?

Thank you.

<img width="938" alt="nms" src="https://user-images.githubusercontent.com/34515240/148105544-c95285f4-107f-4293-9b73-9a098cd64908.png">

### Output of ./validate.php

```txt
is it needed?
```

**Comment by laf** [comment]
Can you provide the output of `./discover.php -h HOSTNAME -d -v -m bgp-peers` and `./poller.php -h HOSTNAME -d -v -m bgp-peers`.

Replace HOSTNAME with the devices hostname.

**Comment by Prolicide** [comment]
[poller_output_firewall.txt](https://github.com/librenms/librenms/files/7827811/poller_output_firewall.txt)
[discovery_output_firewall.txt](https://github.com/librenms/librenms/files/7827812/discovery_output_firewall.txt)
Hi Iaf,
I've annexed the files. Bare in mind that hostname and IP was replaced by "dummy" because it can be sensible information.
Thank you for your help.

**Comment by PipoCanaja** [comment]
Hello @Prolicide 
Unfortunately, CheckPoint is not providing the expected replies to the standard BGP mib, according to your discovery output. Which means that custom code for CheckPoint is probably needed. 

You should play with snmpwalk and see if you can find the OIDs where BGP data is exposed by the FW.

Bye

**Comment by Prolicide** [comment]
Hi pipo,
Doing the following command: "snmpwalk -v2c -c acommunity aHostname 1.3.6.1.2.1.15.3.1" i can get the neighbors:

SNMPv2-SMI::mib-2.15.3.1.1.x.x.x.x = IpAddress: x.x.x.x
SNMPv2-SMI::mib-2.15.3.1.1.y.y.y.y = IpAddress: y.y.y.y
SNMPv2-SMI::mib-2.15.3.1.1.z.z.z.z = IpAddress: z.z.z.z

**Comment by Prolicide** [comment]
hey guys, i think the problem is the following:

SNMP[^[[0;36m'/usr/bin/snmpgetnext' '-v2c' '-c' 'community' '-OQUsv' '-m' 'BGP4-MIB' '-M' '/app/librenms/mibs:/app/librenms/mibs/checkpoint' 'udp:IPADDRESS:161' 'bgpLocalAs'^[[0m]
0.0.0.0

Librenms is polling using snmpgetnext, this gives the first BGP neighbor and not the LocalAS, i can assume the code is validating if the number is an Integer and if not defines that there is no BGP. Using the snmpget gives the correct AS. 
Where can i define this (making sure this change only impacts devices with GaiaOS)?

**Comment by smarques-enxt** [comment]
Hi, can an answer be given on this subject? Are there any alternatives to custom insert the info inside libre??

**Comment by PipoCanaja** [comment]
@Prolicide @smarques-enxt 
For some reason, this code is working correctly on other devices and not on Gaia. You need to understand that first before changing the code.

**Comment by smarques-enxt** [comment]
Yes but no routing info is working for any of our models (Checkpoint 5800, 4800, 12400, 15400, 5100, 16200, 26000, 6200P, etc. etc.) so we need to make a change to fix this.
How would we go by changing the way checkpoint bgp's are grabbed or parsed ?

**Comment by PipoCanaja** [comment]
This is standard code, so again, we need to understand why standard code does not work if Checkpoint implements standard MIB. It would be dirty to do a 2nd "standard" implementation just because there is a bug somewhere (would it be in LibreNMS or in Checkpoint). 
So the process would be: 
- step 1: we understand how everybody is fine with current LibreNMS code except Checkpoint.
- step 2: we find if we can change LibreNMS to fix Checkpoint, keep only 1 implementation of the standard MIB, and not break anybody else.
- step 2 bis: if step 2 cannot be acheived, we go for a checkpoint specific code duplicating the standard mib.

Replacing snmp_getnext with snmp_get seems to be a simple fix, but I am really wondering how it works OK right now everywhere except on Checkpoint ... 

I don't personnally have checkpoint devices, and all of my devices have dedicated BGP (non standard) implementation so they so it will be difficult to do step 1 troubleshooting, and even step 2 (cause I won't be able to check if I break something or not.).

**Comment by Prolicide** [comment]
But where could we make this change? I don't know the librenms code, but in the standard implementation wouldn't fix doing, for example,

Obter Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Prolicide** [comment]
Hi pipo,
Where in the code/file should we be looking at?
Wouldn't it fix it, for example, save the platform OID on a var and make a check on the local-AS that if it's a Checkpoint to run a snmpget instead of getnext? Something along those lines.

Obter Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by laf** [comment]
Should be fixed now as the discovery code was changed to snmpget not snmpgetnext: https://github.com/librenms/librenms/pull/14948
