### ISSUE TITLE
many database entries ExamplePlugin in plugin table

### ISSUE THREAD

**Issue by kristoferus75** [librenms/librenms#14032]
### The problem

Hi !

After reboot of server librenms (webserver memcached rrdcached) there are many database entries in librenms database in table plugins

Select * FROM 'plugins'

ExamplePlugin

thousands of these ExamplePlugin

Seems a bug !

here an picture from phpmyadmin:

![2022-06-13-1655107903](https://user-images.githubusercontent.com/18415083/173309476-b6baf086-b98c-4096-bf76-e9062b5e186e.jpg)

### Output of ./validate.php

```txt
$ ./validate.php 
====================================
Component | Version
--------- | -------
LibreNMS  | 22.4.0-29-g7d3ca7339
DB Schema | 2022_04_08_085504_isis_adjacencies_table_add_index (236)
PHP       | 7.4.28
Python    | 3.8.13
MySQL     | 10.5.15-MariaDB
RRDTool   | 1.7.2
SNMP      | 5.9
====================================
```

**Comment by murrant** [comment]
I'm not seeing this behavior on any of my installs.  Can you try deleting them all and see if they come back?

**Comment by kristoferus75** [comment]
the problem we already delete this entries but this entries come already back  :-( 
we are not sure what is the couse of this problem -> it looks like it happens after a restart of the virt server described above  -> but nut 100% sure

in one situation these entries were drastic high so our librenms web service was extremely slow -> to find out that this was the problem was a challenge

**Comment by Jellyfrog** [comment]
Must come from here; 
https://github.com/librenms/librenms/blob/562af58c7ff173f52c86593b9d285d244d279599/app/Plugins/PluginManager.php#L192-L196

but I dont see the problem, but we should change it to createOrUpdate, and change the schema to be unique by name

**Comment by murrant** [comment]
Really the only possible place it could come from.

Could be an issue here too:
https://github.com/librenms/librenms/blob/562af58c7ff173f52c86593b9d285d244d279599/app/Plugins/PluginManager.php#L210

Adding a unique index with version and name might be the best way to resolve.

**Comment by kristoferus75** [comment]
again 11910 Entries since we restart rrdcached :-(

**Comment by Imperial912** [comment]
thats correct, we have 13.970 Devices in our librenms installation (one Master and 8 Poller) the Plugin Table contains one Entry.
After rrdcached restart and 15 Minutes 100%CPU (128 Threats) the Plugin Table grews up to 11.910 entries and slow down the Website and the Poller.

**Comment by murrant** [comment]
I still can't reproduce this issue.

**Comment by murrant** [comment]
What is the output of `Plugin::versionTwo()->get()->keyBy('plugin_name')` for you guys? (run in lnms tinker)

**Comment by Imperial912** [comment]
$ lnms tinker
Psy Shell v0.11.1 (PHP 7.4.28 â€” cli) by Justin Hileman
>>> Plugin::versionTwo()->get()->keyBy('plugin_name')
[!] Aliasing 'Plugin' to 'App\Models\Plugin' for this Tinker session.
=> Illuminate\Database\Eloquent\Collection {#4746
     all: [
       "ExamplePlugin" => App\Models\Plugin {#4735
         plugin_id: 2,
         plugin_name: "ExamplePlugin",
         plugin_active: 0,
         version: 2,
         settings: null,
       },
     ],
   }
>>> 

we currently use the version 22.4.0, the next maintenance window is set in 4 Weeks because of vacation of many colleagues, including myself ;-)

$ ./validate.php 
====================================
Component | Version
--------- | -------
LibreNMS  | 22.4.0-29-g7d3ca7339
DB Schema | 2022_04_08_085504_isis_adjacencies_table_add_index (236)
PHP       | 7.4.28
Python    | 3.8.13
MySQL     | 10.5.15-MariaDB
RRDTool   | 1.7.2
SNMP      | 5.9
====================================

[OK]    Composer Version: 2.3.10
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[INFO]  Detected Python Wrapper
[OK]    Connection to memcached is ok

**Comment by murrant** [comment]
Can you all test the proposed work-around I sent?  You will need to run `lnms migrate` after applying`
