### ISSUE TITLE
Custom Map Background not visible

### ISSUE THREAD

**Issue by geethreeforce** [librenms/librenms#15868]
### The problem

When i upload a custom background image using the awesome new custom-maps editor, the image is succesfully stored in the database table custom_map_backgrounds as BLOB. When i download and decode the blob, it correctly represents the image. Yet the background image is not rendered. 

### Output of ./validate.php

```txt
bash-4.4$ ./validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.2.0-3-g165af7541 (2024-03-01T00:29:53+01:00)
DB Schema | 2024_02_07_151845_custom_map_additions (290)
PHP       | 8.2.7
Python    | 3.6.8
Database  | MariaDB 10.3.39-MariaDB
RRDTool   | 1.7.0
SNMP      | 5.8
===========================================

[OK]    Composer Version: 2.7.1
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

**Comment by eskyuu** [comment]
Can you please see what happens if you manually try to view the background by adding /background to the custom map URL:
e.g. If your map is https://nmsserver.youre.domain/maps/custom/3, please check to see what happens if you open https://nmsserver.youre.domain/maps/custom/3/background

Assuming the above works, can you please open developer mode in your browser and look for the /background URL that your browser is trying to open when opening the custom map.  It uses the base_url global setting, and I'm wondering if yours is either set incorrectly, or possibly missing a trailing /.

Can you please check these 2 things and let me know what you find.

**Comment by geethreeforce** [comment]
Hi. The url to my custom map shows the map without background. 
https://noc.***.eu/maps/custom/3 when adding /backgound: https://noc.***.eu/maps/custom/3/background i'm greeted with the Whoops, looks like something went wrong. Check your librenms.log error.

**Comment by eskyuu** [comment]
That's weird because the php script checks that the file exists and should create the file if it's not there.

Does /opt/librenms/html/images/custommap/background/ exists and is it writeable by the web server / librenms user?  And are there any other errors in the librenms.log file that may indicate an error writing the file above?

**Comment by geethreeforce** [comment]
Hi. The folder is there. When i put the expected outputfile there manually, the background is visible. 
Here are my /opt/libernms/html/images/custommap permissions:
_drwxr-xr-x  4 librenms librenms    37 Feb  1 00:19 custommap/_

And the permissions of the folders inside /custommap
_drwxr-xr-x  4 librenms librenms   37 Feb  1 00:19 ./
drwxr-xr-x. 9 librenms librenms 4096 Mar  1 13:35 ../
drwxr-xr-x  2 librenms librenms   39 Mar  7 15:44 background/
drwxr-xr-x  2 librenms librenms  159 Feb  1 00:19 icons/_

There are no more errors visible, than the one i posted in my previous reply. 
For now i've developed a workaround.
I'll describe the workaround in a separate post.

**Comment by geethreeforce** [comment]
Custom Map background image not visible:

**Problem description**
When adding a background image to your custom map, the image is not visible. 
When checking the database, the image is there and converted to BLOB. When downloading and manually converting the BLOB, back to image the image is rendering as expected.
The required folder /opt/librenms/images/custommap/background is there and the permissions are set correctly. 

**Workaround**
The workaround is a bit tedious, but works. 

1. Create your custommap and add a background image
2. Save your map
3. View your map: for example:  https://nmsserver.youre.domain/maps/custom/3
4. SSH into your LibreNMS change user to your librenms user via: sudo su librenms host and browse to /opt/librenms/logs
5. Now type tail -f 
6. Now add /background to the end of your url https://nmsserver.youre.domain/maps/custom/3/background and watch the tail for an error looking like this: 
 _"/opt/librenms/html/images/custommap/background/3_3.png" does not exist {"userId":68,"exception":"[object] (Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException(code: 0): The file "/opt/librenms/html/images/custommap/background/3_3.png" does not exist at /opt/librenms/vendor/symfony/http-foundation/File/File.php:36)"}_
7. Make note of the expected image path and filename: **/opt/librenms/html/images/custommap/background/3_3.png**
8. Now manually upload the file under the mentioned filename to the expected path, using a SSH file manager of choice. I personaly use Filezilla. 
9.  The background image is now visible.

**Comment by eskyuu** [comment]
Can you please try chmod 777 /opt/librenms/html/images/custommap/background/
If this works, can you please show the owner of the image file created?

**Comment by geethreeforce** [comment]
777 is a too much ;-) 
I've changed the permissions on the /opt/librenms/html/images/custommap/background/ to 775 (more secure). 
That did the trick. 

So the most applicable solution is to change the permissions on the directory to 775 
Thanks for your help!

**Comment by geethreeforce** [comment]
The issue was caused by a permission problem.
Final solution: change permissions by issuing the command below. 

_sudo chmod 775 /opt/librenms/html/images/custommap/background_

**Comment by eskyuu** [comment]
The chmod 777 was intended as a test to check whether it was a permission error or not.  Luckily your php user must be in the librenms group, so group write access was enough to confirm the issue.

I'm guessing that your installation differs from the install guide below which says to use php-fpm running as the librenms user:
https://docs.librenms.org/Installation/Install-LibreNMS/#configure-php-fpm

Can you please confirm your PHP config (e.g. are you using FPM, or a web server module?) because I'm guessing other people will have a similar setup, and I'd like to push an appropriate change into the code.
