### ISSUE TITLE
Cisco Stack state errors on unstacked device

### ISSUE THREAD

**Issue by ShaneMcC** [librenms/librenms#16374]
### The problem

Since f54e38f4fe4de38e97e5f30e21053fb1223f4744 librenms has started reporting errors with stacking state on an unstacked Cisco switch.

That commit changes the value of `$tablevalue['oid']` to now be a complete oid (eg: `CISCO-STACKWISE-MIB::cswGlobals` rather than `cswGlobals`) and now the `if` statement no longer correctly excludes the OIDs.

The if statement on `line 43` should probably either be changed to look for any `oid` starting with `CISCO-STACKWISE-MIB::` or to add `CISCO-STACKWISE-MIB::` to the 4 conditionals.

### Output of ./validate.php

```txt
n/a
```

### What was the last working version of LibreNMS?

81d6eb57e68fa78f5ce94a0888f7521512f7b039

### Anything in the logs that might be useful for us?

```txt
n/a
```

**Comment by ez-w** [comment]
Hi,

I don't know if it's related, since 2024-09-04 00:37:11 => I have sensor critical alerts under and over limits for all my Cisco routers (Cisco IOS XR Software (NCS-5500)). 
If I change the limits of these sensors to make the alerts disappear, they return to the default values ​​and therefore again on alert, the next day when the equipment is discovered again.

**Comment by wat-doing** [comment]
We're also receiving errors across our entire fleet of IOS devices that don't have stack cables.  Hundreds of alerts every poll cycle.  Following here for update.

**Comment by laf** [comment]
Well spotted Shane :)
