### ISSUE TITLE
Navigation bar overlaps with the device info.

### ISSUE THREAD

**Issue by javieraubert** [librenms/librenms#16719]
### The problem

When having several services actives the navigation bar don´t fit in one row so it overlaps with the content space, try it on Chrome, Edge and Brave, same result.

![image](https://github.com/user-attachments/assets/94a93c04-3f0f-4c65-9ac3-3e2ba765c827)

### Output of ./validate.php

```txt
librenms:~$ /opt/librenms/validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.9.0 (2024-10-15T13:15:45-06:00)
DB Schema | 2024_08_27_182000_ports_statistics_table_rev_length (300)
PHP       | 8.3.8
Python    | 3.11.10
Database  | MariaDB 10.5.27-MariaDB-ubu2004
RRDTool   | 1.8.0
SNMP      | 5.9.4
===========================================

[OK]    Installed from package; no Composer required
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    No python wrapper pollers found
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
[WARN]  Non-git install, updates are manual or from package
```

**Comment by murrant** [comment]
This depends on the browser width and the number of menu items.  LibreNMS hides icons/text when the browser width gets lower.  I don't think it is possible to have that work perfectly in every case.

**Comment by jaxcentracom** [comment]
It looks like this is caused by the navbar having the class "navbar-fixed-top". I am not very good with CSS but it looks like having the position fixed causes things to not align properly when the navbar expands. If I delete that in web developer tools it does mess with the alignment but that mainly seems to be because the body has a "padding-top" of 50px. When I remove that it seems to align things properly.

Does anyone know why there is a padding of 50px on both the top and bottom of the html body? I don't have a development environment setup for LibreNMS so I can only test the changes in the web browser development tools and I can't check every page to see if breaks something. Also the spacing is kind of weird if you don't delete the br element between the navbar and the div with the rest of the page content.
