### ISSUE TITLE
Thoughts on having a dev branch

### ISSUE THREAD

**Issue by laf** [librenms/librenms#1840]
I Know this isn't a favorite with everyone but what do people think about us running a dev branch where all commits would normally be merged to then we merge to master once or a week or so?

The reason I bring it up is due to a couple of PRs we've had to roll back now which could / would have been identified with people running them on a dev branch. Some users want stability and some want breaking features and support. This would give us the best of both those worlds but also but means we get a wider test audience when something gets pushed to dev.

Thoughts?

**Comment by Lucheni** [comment]
I think it would be a good idea to separate into two branches, but right now so many things are happening with LibreNMS (rapid development, it's good!) that it would probably end up creating confusion in regards to support and documentation. 

A weekly merge to master could also mean that documentation needs to be updated weekly in terms of new features or adjustments to prior ones. And since you are already creating monthly changelog reports, it might be better to do a monthly merge and base needed documentation changes upon that.

**Comment by f0o** [comment]
:+1:

**Comment by paulgear** [comment]
Whilst I don't really want to do this, if it is what most of our users want, we should consider it.

We may want to default to the unstable branch, because I suspect that most of the support requests we get in IRC and the mailing list are from people who are a) doing their initial install, or b) trying to set up a new device type.  We can mostly fix a) by having a better install process, but b) really requires that people be on the branch that we're running.  However, the folks who are maintaining distro ports would probably prefer to pull from stable.  Whether we want to do it from different git branches or completely different repositories is a question we need to think about.

I don't think the documentation issue should dictate the weekly vs. monthly choice; if we simply ask that people add a one-line description of their fix to the change log with PRs, it will reduce the work in maintaining the change log, and allow us to merge as often or as seldom as we like.

**Comment by regnauld** [comment]
Having something that is easier to "stick" to and allows users to move from stable to stable would be welcome in my book. We teach LibreNMS as part of our Network Management & Monitoring curriculum at the Network Startup Resource Center (http://nsrc.org), and one of the issues is that we have to download & test a snapshot of LibreNMS, and run it against our labs before we can greenlight it. It'd be great to that a particular revision/tag/branch is always going to be stable.

For reference, this may help http://nvie.com/posts/a-successful-git-branching-model/

Cheers,
Phil

**Comment by SaaldjorMike** [comment]
Is this still needed after #2487 that gives you the option to follow tagged releases instead of master branch?

**Comment by regnauld** [comment]
#2487 solves my particular issue with regard to tracking stable versions. I can't answer on behalf of @laf whether the wider scope/discussion on the benefits/downsides of having a dev branch is still required.
