### ISSUE TITLE
Manual update error

### ISSUE THREAD

**Issue by macbook8** [librenms/librenms#1852]
root@nms-lb:/opt/librenms# git pull; php includes/sql-schema/update.php
Updating 9073cf5..4d3f86e
error: Your local changes to the following files would be overwritten by merge:
        includes/defaults.inc.php
Please, commit your changes or stash them before you can merge.
Aborting

**Comment by f0o** [comment]
First of all, we strongly disadvice against using the update.php directly.
Chances are high that it may cripple your sql because you skip all sanity checks.

Secondly, dont modify files without knowing how to git stash and git stash apply.

On September 5, 2015 4:59:50 PM GMT+02:00, macbook8 <notifications@github.com> wrote:
>root@nms-lb:/opt/librenms# git pull; php includes/sql-schema/update.php
>Updating 9073cf5..4d3f86e
>error: Your local changes to the following files would be overwritten
>by merge:
>        includes/defaults.inc.php
>Please, commit your changes or stash them before you can merge.
>Aborting
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/1852

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by macbook8** [comment]
Thank you for your reply.

How to update LibreNMS?

**Comment by f0o** [comment]
The recommended way is using the daily.sh 

On September 5, 2015 5:04:19 PM GMT+02:00, macbook8 <notifications@github.com> wrote:
>Thank you for your reply.
>
>How to update LibreNMS? 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/1852#issuecomment-137963440

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by paulgear** [comment]
@macbook8, please also note that you shouldn't be modifying includes/defaults.inc.php - the correct way is to copy the lines of interest into config.php and edit them as desired, leaving includes/defaults.inc.php untouched.

**Comment by Rosiak** [comment]
I'd say this issue can be closed.
