### ISSUE TITLE
Network map

### ISSUE THREAD

**Issue by acidsas** [librenms/librenms#1909]
Right now we use FPinger to draw a network map and provide visual and audio alerts to support personnel. Cacti for graphing. I would like to move to librenms completely. So a map with devices and links added by hand would be awesome. We also have some web managed switches, which do not support snmp.

**Comment by laf** [comment]
This is possible but needs work, you can store the coordinates using visjs which is what we use for the new style map.

**Comment by gelato** [comment]
Agreed, it would be cool to supply a way to manually draw a network topology map, maybe based on already drawn auto-map.

**Comment by khobbits** [comment]
I thought it would be nice to be able to do the same, after a bit of web searching I stumbled on this:
https://github.com/librenms-plugins/Weathermap

When adding a 'node' you get to select from the devices in LibreNMS, and when adding a link, it asks you which interface on the device you want to use for the 'usage'.

While the 'editor' is a bit clumsy I created a map with about 22 nodes, with the relevant links in less than an hour.

**Comment by gelato** [comment]
It's quite ugly, buggy and might eventually just stop working.
I'd love to see the same solution from LibreNMS's authors, because now LibreNMS's network map is unusable - once you add enough nodes it becomes one big not informative mess. I'd love to see node grouping, sorting, static placement of nodes according to network core, basically i'd love to see usable network map.

**Comment by khobbits** [comment]
I was thinking the single best improvement is to graph 'groups', rather than just every node.
That way I could add the devices I wanted to see to a group, and reduce the clutter.
At 66 switches, the resulting diagram is already becoming unreadable.
The idea of saving a layout is cool, but it would probably require a more complicated graphing system.

**Comment by joseaugustocardoso** [comment]
I think that Cisco NeXt UI can be useful, its a topology framework
https://developer.cisco.com/site/neXt/

**Comment by laf** [comment]
Issue moved to [librenms/librenmsv2 #177](https://github.com/librenms/librenmsv2/issues/177) via [**ZenHub**](https://www.zenhub.com/)
