### ISSUE TITLE
Polling bug causes too many connections in Mysql DB

### ISSUE THREAD

**Issue by justnx** [librenms/librenms#1920]
after running my Librenms instance around 8 hours, i recognized that the polling seems stop working again and again with Message "ERROR: Could not connect to Mysql".

Reason: ERROR 1040 (08004): Too many connections
Librenms poller-wrapper (poller.php) is creating 3000 sleeping connection to my Mysql Database like this which doesn't seem not get closed probably:
 3126 | librenms | localhost | librenms | Sleep   |   465 |       | NULL             |    0.000

A temp workaround for me was, lowering mysql wait_timeout, interactive_timeout but that's surelly no solution but to prevent running out of max connections.

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On what commit are you?

On September 17, 2015 9:26:39 AM GMT+02:00, Julian Sternberg <notifications@github.com> wrote:
>after running my Librenms instance around 8 hours, i recognized that
>the polling seems stop working again and again with Message "ERROR:
>Could not connect to Mysql".
>
>Reason: ERROR 1040 (08004): Too many connections
>Librenms poller-wrapper (poller.php) is creating 3000 sleeping
>connection to my Mysql Database like this which doesn't seem not get
>closed probably:
>3126 | librenms | localhost | librenms | Sleep   |   465 |       | NULL
>            |    0.000
>
>A temp workaround for me was, lowering mysql wait_timeout,
>interactive_timeout but that's surelly no solution.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/1920

- --
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJPBAEBCgA5BQJV+m0HMhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikg
PGYwb0BsaWJyZW5tcy5vcmc+AAoJEJMZKtVWOFzBB3cP/1WoSrJf/4QG1SHGyDlG
a8o3o1ireBKR0I0r6f8F89qzQlX/9fZvg6zyyBRnGMMTf4K4IjrijVzdm1c5QpgR
twUJGDbqnLK9w9tGwZlbv+t/GSomRDJTPg0FIu/wIkZQifJgMFZApKmPMlJ/pa69
jsdhCS46MB0Q11CypPjfSO+oIj9ay6jRSZUhriwMaoK4aPRpLU37vNNYBeDqXNHZ
h41J0RMpjOSEKIATBMVGx44twn4vo7hikvwurIZaThM+fBR5ZrD49di/Fv4OpSft
kUHPxKqs+cJQTmtkdncFcN8NSSO4yukt5OogfYioSrR4DqqCAOPgk7l2NpE5xgVw
9mfoH8K7hxaUqi5N7qEfS4hdOeC2oYKeFQT0GfMchZwrG7s8mLZtFLn7FhwRKB9Q
lZvhkciEhsDnT7Z9x4EjLB1U6zc02Dzc9vDQtWwPBgCI8oTRNVchB3Js14Qe6u2g
hqQZQuQOnhYAVg6tacMCzEZtiecyWD+Q+Bgab2V7VgpXWprdil90IA3Elc6rh5iE
WPCA7Ujc5NlG9Po2YU5uKBXRDEyp5R9xQ/e8YlhhOyXd0dVhXmlvh5iXUk6FpBhB
6h3Qps1ewucIhP/2uCUySIznlxsqTmO8tJG070VppiX7xQ6VuABIZ5na6U4aK/xg
64mhPKDLVqEmAGOGZx957cwl
=qjbB
-----END PGP SIGNATURE-----

**Comment by justnx** [comment]
I'm on the latest from .git if you meaning that.

**Comment by f0o** [comment]
Could you please paste us the commit hash?

Also can you tell us about your setup? What distro, MySQL server, Cronjobs, ...

Thanks

**Comment by justnx** [comment]
Commit hash is: 409ee518207943511cef1974b3f782eacec67aea

Debian Wheezy (7.9) running MariaDB 10.0.21-MariaDB-1~wheezy

Cronjobs:
33  */6   * * *   librenms    php /opt/librenms/discovery.php -h all >> /dev/null 2>&1
*/4  *    * * *   librenms    php /opt/librenms/discovery.php -h new >> /dev/null 2>&1
*/5  *    * * *   librenms    python /opt/librenms/poller-wrapper.py 16 >> /dev/null 2>&1 
15   0    * * *   librenms    php /opt/librenms/daily.sh >> /dev/null 2>&1
*    *    * * *   librenms    php /opt/librenms/alerts.php >> /dev/null 2>&1
*/5  *    * * *   librenms    php /opt/librenms/poll-billing.php >> /dev/null 2>&1
01   *    * * *   librenms    php /opt/librenms/billing-calculate.php >> /dev/null 2>&1

**Comment by f0o** [comment]
off topic: `15   0    * * *   librenms    php /opt/librenms/daily.sh >> /dev/null 2>&1` is not going to do anything at all.. it's a shellscript not a php script.

I'm on a jessie and mariadb with the poller-wrapper as well and cant see those huge numbers, do you have any special configs (php.ini changes, mysql changes, ...?) or than defaults?

**Comment by justnx** [comment]
you are right, my fault/typo ;-)

well its running on nginx/php5-fpm, so nothing special. i run those setups often but with observium since i found this new community fork and also had never such trouble with idling connections.
i also changed mysql connector from mysqli to mysql, maybe this made it break out.

**Comment by f0o** [comment]
Odd...
I just doublechecked my installs all idle around 3-15 cons, 3 at least and peaks when poller runs to 15.

Also nginx+fpm+mariadb and wheezy&jessie&centos7 :/

Can you see anything in the logs?
Do the poller.php's terminate or do they keep in your processlists?

Further debugging can be done by disabling the cronjobs and restarting the mysql verify that con-count is low/stable then run poller-wrapper.py manually as librenms user and recheck the con-counter

**Comment by justnx** [comment]
so they yours arent in sleep state?
look at mine, they keep raising in time:
+------+----------+-----------+----------+---------+------+-------+------------------+----------+
| Id   | User     | Host      | db       | Command | Time | State | Info             | Progress |
+------+----------+-----------+----------+---------+------+-------+------------------+----------+
|   37 | librenms | localhost | librenms | Sleep   |  383 |       | NULL             |    0.000 |
|   38 | icinga   | localhost | icinga   | Sleep   |    0 |       | NULL             |    0.000 |
| 2345 | librenms | localhost | librenms | Sleep   |  383 |       | NULL             |    0.000 |
| 2346 | librenms | localhost | librenms | Sleep   |  372 |       | NULL             |    0.000 |
| 2350 | librenms | localhost | librenms | Sleep   |  223 |       | NULL             |    0.000 |
| 2357 | librenms | localhost | librenms | Sleep   |   70 |       | NULL             |    0.000 |
| 2358 | librenms | localhost | librenms | Sleep   |   68 |       | NULL             |    0.000 |
| 2365 | root     | localhost | NULL     | Query   |    0 | init  | show processlist |    0.000 |
+------+----------+-----------+----------+---------+------+-------+------------------+----------+
and it seems they raise the longer the cron runs.

**Comment by justnx** [comment]
some time later:
+------+----------+-----------+----------+---------+------+-------+------------------+----------+
| Id   | User     | Host      | db       | Command | Time | State | Info             | Progress |
+------+----------+-----------+----------+---------+------+-------+------------------+----------+
|   37 | librenms | localhost | librenms | Sleep   |  648 |       | NULL             |    0.000 |
|   38 | icinga   | localhost | icinga   | Sleep   |    1 |       | NULL             |    0.000 |
| 2345 | librenms | localhost | librenms | Sleep   |  648 |       | NULL             |    0.000 |
| 2346 | librenms | localhost | librenms | Sleep   |  637 |       | NULL             |    0.000 |
| 2350 | librenms | localhost | librenms | Sleep   |  488 |       | NULL             |    0.000 |
| 2357 | librenms | localhost | librenms | Sleep   |  335 |       | NULL             |    0.000 |
| 2358 | librenms | localhost | librenms | Sleep   |   33 |       | NULL             |    0.000 |
| 2410 | librenms | localhost | librenms | Sleep   |   30 |       | NULL             |    0.000 |
| 2418 | librenms | localhost | librenms | Sleep   |    8 |       | NULL             |    0.000 |
| 2419 | root     | localhost | NULL     | Query   |    0 | init  | show processlist |    0.000 |
+------+----------+-----------+----------+---------+------+-------+------------------+----------+

**Comment by f0o** [comment]
we exclusively use pconnect for the sqls, if that fails there must be something seriously wrong with your php environment.

Could you please check if the poller processes terminate (not sql-related) and dont idle around or worse, defunct ?

Also we recommend using mysqli as PHP itself said that the mysql connector is EOL

**Comment by justnx** [comment]
pconnect might be the problem on special constellations. that also explains why there is no trouble when using mysql instead of mysqli connector.

as i said, there aren't any poller.php zombie processes.

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

You said you only have default configs and setup. For that it wont cause issues.

Please elaborate your setup.

I can verify that these work without issue:
- - debian (wheezy,jessie,stretch) apache2|nginx modphp|fpm oracle-mysql|mariadb replication|galera (codership, mariadb and percona)
- - CentOS (6.0,6.5,7.0) apache2|nginx modphp|fpm oracle-mysql|mariadb replication|galera (codership, mariadb and percona)
- - Gentoo 2.2 apache2|nginx modphp|fpm oracle-mysql|mariadb replication|galera (codership, mariadb and percona)

I have a percona-xtradb galera cluster on my install behind a keepalived vip and barely get over 30 cons in total while monitoring 200+ servers using distributed pollers.



On September 18, 2015 10:41:46 AM GMT+02:00, Julian Sternberg <notifications@github.com> wrote:
>pconnect might be the problem on special constellations. that also
>explains why there is no trouble when using mysql instead of mysqli
>connector.
>
>as i said, there aren't any poller.php zombie processes.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/1920#issuecomment-141382555
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJPBAEBCgA5BQJV+9JvMhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikg
PGYwb0BsaWJyZW5tcy5vcmc+AAoJEJMZKtVWOFzB+2AP/irc7mf+pz1qKhew2+kP
xjq4RgVUa6Swb4Vux9jyPFeUy7Q6Eq98s6RIeFeZTFibqHSC9hncfihmTbQF1kEn
B+EJJTVqriFrIqUp2EW1a0bwEaeGGdk/NnVSiUkyfwfuBS4bqVwtZPHvS5ze+OGb
KJgwKEwP3FAK6EIgNvEQUXS0td850Qpyu3wvkCiCqLJtUAB4U2oPxakDBxTSaObm
Jy41P878IPeo8jelX6IHw7Z4RfMI48LNaHnqXHsd/reRtsYbkRUYcLYCz0DNRBB0
eIufaV9/3jMUOGzj4Nzp3wm+9s3bl59PrJPM6wdZsVgvCYlEZBe+0RFDwVEPnDdg
K287gTobxIE8FhyuLpnokPBtDMwTc+EpX2+MDHdjDKulUxShyEE2YvnzA2HgpC8J
6aFZmcFTnqGQvlakg3mU/mcBZ5HH+WInMKVfc0rU7LRImdUMoReq0qy5PbBR4uut
UaKi4ODIIXEhbQ/7WB/HSNcsE4EGKJOjRB2HgprmmHBglb+uDKjNI5OtrYFA8mOl
rzZx1R7A5aIHqOe5mEhEpBUxqsDEYjXLzD5Qy/k3Cwj2NtAX95XL1YB/NjRaQNO/
Wskkz+Qe8Z8rCKs2aB1F7sMXV8R5dL1rQhIruZnE2bBxlYBddUIUEuaFCtxnz5VD
cxZDy/TyoYrSoSdoxdgG3f+4
=HPtI
-----END PGP SIGNATURE-----

**Comment by laf** [comment]
Any further update @justnx or can we close this?

**Comment by laf** [comment]
Closing, please feel free to re-open.

**Comment by MHammett** [comment]
I am having this problem as well. I have pasted below the MariaDB version, the Debian version and the output of show processlist


root@LibreNMS-MySQL:/opt/librenms-agent/agent-local# mysql -v -u root -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 32675
Server version: 10.0.22-MariaDB-0+deb8u1 (Debian)

Copyright (c) 2000, 2015, Oracle, MariaDB Corporation Ab and others.

Reading history-file /root/.mysql_history
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> exit
Writing history-file /root/.mysql_history
Bye
root@LibreNMS-MySQL:/opt/librenms-agent/agent-local# cat /etc/debian_version
8.2

[LibreNMS Too many MySQL Connections.txt](https://github.com/librenms/librenms/files/74974/LibreNMS.Too.many.MySQL.Connections.txt)


I was going to post a file with the output of ps aux, but redacting it became too much work. There are:
141 instances of "/bin/sh -c    /opt/librenms/discovery.php -h new >> /dev/null 2>&1" and "php /opt/librenms/discovery.php -h new"
286 instaces of "/usr/bin/snmpget"

**Comment by VimCommando** [comment]
I think we ran into this last night as well on an AWS setup we are putting together. We are using a LibreNMS Docker image (https://github.com/jarischaefer/docker-librenms) pointed to a MySQL Amazon RDS instance. Last night we ended up with a slowly (over about ~6 hours) growing pool of connections that spiked to over 170 connections (more than 10x the 16 configured pollers). Eventually our service died with a MySQL "too many connections" error.

We have since reset our services and are consistent around 12-15 connections for the last two hours. It sounds like this may be an uncommon but still unresolved issue, so I will be sure to provide more detail if we hit it again.

**Comment by VimCommando** [comment]
So we did figure out our problem, so for the next person who runs into this, I'll leave some insight. We were able to recreate the problem on two separate database instances, one shared MySQL, and one dedicated MariaDB. Since we only have about 120 devices monitored, we did not expect to run into this kind of scaling issue yet. We were running mostly out-of-the-box configs with 16 pollers.

It doesn't look like this is a bug so much as not gracefully handling long-runing polling operations; this causes over-saturation of DB connections. To start, here is our connections graph from AWS.

![aws_db_connections](https://cloud.githubusercontent.com/assets/1674688/21148660/2ebe21fa-c116-11e6-8841-b71c640f94c1.png)

As you can see for the first several hours everything seems to be running ok, with only a slight rise in the average number of connections. Just before 08:00 something important happens: we get more than 16 sites (our number of pollers) that take longer than 300 seconds to complete polling. This causes the next batch of pollers to stack _on top of our existing connections_. 

So in effect we get 32 pollers, _not 16 as configured_. We continue with the 32 until _those_ polling devices are taking longer than 300 seconds, and then spin up a 3rd set of 16 pollers about 15 minutes later. This cycle continues until we hit our server's maximum of 150 connections at 12:00.

You can see the effect this has on individual devices in the graphs below, one from a long-polling device, and one from a short-polling device.

![long_polling_device php](https://cloud.githubusercontent.com/assets/1674688/21148666/348cce06-c116-11e6-9adc-7d710fdf9587.png)

_(DISCLAIMER: I know the graph time zones are off, but I assure you it is the same time period. We later fixed our PHP vs. Docker vs. System timezone issues.)_

Our long polling sample device starts at around 140 seconds and maintains a fairly steady response until 22:00-01:00. In this time period our DB connections were on the rise, slowly pushing the response time up. As DB connections grew, the response times skyrocket to peak over 900 seconds (3x our polling cycle of 300 seconds).

![short_polling_device2 php](https://cloud.githubusercontent.com/assets/1674688/21148672/39ba3b5c-c116-11e6-8abb-9d7bc6100158.png)

Here the short polling device, starts at around 30 seconds and grows to _more than 12x_ it's polling duration once the DB has become connection-saturated. We tried the wait_timeout and interactive_timeout settings as suggested, but they had limited success. It would kill the sleeping SQL connections, but _not_ the sleeping PHP processes from the Poller.

The gaps in both graphs are combinations of missed polling cycles and host flushes from the DB. We finally reset the whole service in that last hour, and as you can see it was trending up almost immediately.

Eventually we did find an equilibrium for our server. Our Number 1 fix? Disable polling modules. Turns out there were a lot of things we didn't need globally enabled. The _Ports_ module was the single biggest offender. As we pared it down to the necessities, and only selectively enabling _ports_ where we needed it, we got our typical response (80+ devices) under 30 seconds, and only 1 device over 100 seconds.

Our Number 2 fix? Cut our pollers from 16 to 8. We are only running a dual-core instance, and the front-end is shared with another application we are serving.

This is a week look at the same Long Polling device _after_ our cleanup and reconfigure.

![long-polling-after](https://cloud.githubusercontent.com/assets/1674688/21149980/b7c01d10-c11a-11e6-89da-a95c6b242ead.png)

You can still see the giant spike in response from last week, but how it has been stable ever since.

While I think we are in a healthy state, I think the _one_ thing that could be improved might be is how poller subprocesses are handled when they exceed the polling time. Or even if it can be configured. I know the poller.php script does not enforce a max execution time, and the initial configured poller number is not enforced by any means (each poller.php also spawns 4x rrd-tools) so it can quickly overwhelm a system.

Hopefully this helps someone else in the future.

**Comment by laf** [comment]
An absolutely massive thank you for your detailed and thorough investigation of this. I'm going to re-open the issue and see if we can't do anything to alleviate this at some stage.

**Comment by MHammett** [comment]
I no longer have that monitor, but I too had really long polling times on some devices, which only escalated the issue.

**Comment by shimamizu** [comment]
I've just run into this as well on a POC instance I've deployed to see if we should deploy LibreNMS for the whole department or not. It's also pegging the RAM after I get new devices in. A reboot seems to alleviate it, but that isn't really ideal if we go production with this at some point...

**Comment by laf** [comment]
Have you followed our performance doc and the suggestions here?

**Comment by laf** [comment]
Ok here's one possibility on how to approach this.....

Rename the rrdtool step config value to 'poller.frequency' so that it indicates how often polling is run (we can't control the user has changed cron to match here but we should suggest that this value needs to match). Then using this value, we keep a track of the total running time of a poller (distributed would also work here), as soon as the running poller time hits poller.frequency - 2 value then we remove the remaining devices from being polled that cycle, clean up and exit the poller-wrapper.py script.

What do people think to this @librenms/reviewers ?

**Comment by laf** [comment]
I'm closing this issue, I think we've come a long way since the original post with various performance optimisations that have either made it into the default core or is documented on how you can improve performance.
