### ISSUE TITLE
Reboot device using SNMPv3

### ISSUE THREAD

**Issue by 21let** [librenms/librenms#1929]
I had an idea for a feature (maybe longer exists and I do not know about it):

Using SNMPv3 might be an option to reboot the device directly from librenms (by clicking on the button reboot).

**Comment by Rosiak** [comment]
Personally I don't think this is a good idea.

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I agree with @rosiak.

The NMS is supposed to monitor not to administer. Maybe this is something that should be a plugin rather than included into the core.

On September 18, 2015 6:17:37 PM GMT+02:00, "Søren Rosiak" <notifications@github.com> wrote:
>Personally I don't think this is a good idea.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/1929#issuecomment-141497023

- --
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJPBAEBCgA5BQJV/EHrMhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikg
PGYwb0BsaWJyZW5tcy5vcmc+AAoJEJMZKtVWOFzBdBMP/ih5sRj7YDqCu4RzQcR1
eO8haIOAzGMWTAQ0Ki74Ibnhh7OllYcoHzJCAH9d8K5yWcTMKR8tid/Y1LIz6z22
f5UQE7Qwk329kAI5KGG2lHG797wHc/oQc2rdT8eT7HI5fxEn7rdHFin9+h1tKBCD
KSKbPEhczgqvPFoR+XAOLkN1ZLW3i9Z9MJ4rBt5PZ0aON0fUBE8WdV5aa7pmCK8H
CJLr5B6d+DJKWV2Lfk9uT0UMqcIvLpg1b1Y1aQTy9ipkxBeNx9mgssapCCZwT8dr
iHZ0Wm/ITtNcPaF2ttkLPZ/uYuKYNNl+6iXLEN/uv8HJznQ8JKUBJhv/BZTFT14m
ShoTsglon4I8/gaQ1eD0EfinXxyYrxcE8mpgl8Maa7xUD9LLQisAEzt6CJSfIndo
IySMCBKTu1cdTXp9xRrjJ+jzRfFJf+/QmR8nxFxhrFPYVh3kZUTqil1Foah7lfZE
GfrZC5/C+8oUA4sF8X50b+JbFNPmYfsjHpKfxU/vtAKYtEYLPnNBtMc6znaHw96r
oBNTnF85/nlhDvLwPU+sWYzNCg8Ddtgo0oSGapurXYmts0cfSj+KDfchdsKpi2P/
k1dn9btIR6c9LtUhW52x2NCVuTvlDwtem/PEVaoONp6Ql7ull6T4KT6fgibmBrff
d6U6nDjfwlW7/y6GX6w6SE3j
=3/tv
-----END PGP SIGNATURE-----

**Comment by masonke** [comment]
The idea of an NMS being able to reboot a device is VERY scary.
~KEM

**Comment by Tawmu** [comment]
I don't know about other people, but I'd be concerned about this opening up device reboots for your entire network behind (potentially) a single password.

**Comment by 21let** [comment]
Function could be easily switched on or off, after all, if someone does not use snmp with write permissions, so there is no problem here that anyone would perform remote reboots. If you can in detail be able to access via SSH, etc., so why should not the ability to remotely reboot?

**Comment by masonke** [comment]
You are betting on the coding ability of others to have a bug free operation. You also greatly increase the ability to have an “OOPS"
~KEM

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

By all means, I strongly disadvice giving an NMS so much 'power' over your gear.

Assuming it would be a config flip, the only thing that prevents an attacker to reboot all your snmp3 rw gear is merely another password namely the ssh of librenmsbox. This is NOT good.
If I had a veto, I'd call it for this.

If anyone like to have this feature then please code it as a plugin and release it yourself or send it to us and we make a librenms-plugins repo for that.

Personally I dont want to see this shipped with the core.

Greetings from Sverige,
Daniel

On September 18, 2015 11:44:54 PM GMT+02:00, Kevin <notifications@github.com> wrote:
>You are betting on the coding ability of others to have a bug free
>operation. You also greatly increase the ability to have an “OOPS"
>~KEM
>
>> On Sep 18, 2015, at 16:45, 21let <notifications@github.com> wrote:
>>
>> Function could be easily switched on or off, after all, if someone
>does not use snmp with write permissions, so there is no problem here
>that anyone would perform remote reboots. If you can in detail be able
>to access via SSH, etc., so why should not the ability to remotely
>reboot?
>>
>> —
>> Reply to this email directly or view it on GitHub
><https://github.com/librenms/librenms/issues/1929#issuecomment-141563604>.
>>
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/1929#issuecomment-141576153
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJPBAEBCgA5BQJV/TIAMhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikg
PGYwb0BsaWJyZW5tcy5vcmc+AAoJEJMZKtVWOFzBuZgQAI7Tjr52Z1dI7JmWUpTN
RgApAULPss6LhfGNb/JZ+Ua2dKT/+VKAUAiUy1P5RRqqGlRXrQBLz6U7xZBaS0EY
+rcsflCC3kJvyJkd2CMcFZDBMQFqto0BMPKXnYhVfH42bN9f0lfU5OuHDxyJCCBf
y23U2U5LbJFOkRKa3fEa9tZZ/9R1gx/quu4fKcnRJAife4gdHp6skDl2e4bq4M6H
Mm7WUGDsgMhWrEDpr5p+Ef/6NS2hbY1xXdYpcESf+zXP3gC/sM5rEVz4hZCSusQc
A/nrxrpi9G+BQdFhBTDukUd/iz7DVI3hg2h/LNfSTPkUJNq8dnaL38QoPj7PYDrn
ss1+NMNI1vbgISlwPI+y9yRgUsLvQTdTlUeG09qspdJEIdYZaFPELtGKAC+9xfPp
K00CagevzYn8ZhDHhF4IJlk5+N/l6gdj5r+BzvcrsOSZB8Wu4cRJ3+Vg49lTNcfK
KipNpAXdGJZ9PZo2Te8v++nHEWun4MeuY9eBW8gnjqnHikeluL3te3bhbzBfesfb
2kqJQOZGdxRMXhplgPNOadCtN4RJOfzgtyo/uyKf7NsSqFOxDZvBdY0rAX94aTHD
NULGOgk58JZeWIdHjDOzToHMRKR/H/dcSYXqvKqv4jyUQgqujhljsQBGNCPKvQ/p
pGZS9aybDoD8uQS2HwyvjuF1
=hiLm
-----END PGP SIGNATURE-----

**Comment by 21let** [comment]
So I'd closed the debate so that the plug has done and who will be interested, you can install it. thank you

**Comment by Rosiak** [comment]
As far as I understand, this issue can be closed.
Please let me know if I'm mistanken.
