### ISSUE TITLE
add support for control tags in subject

### ISSUE THREAD

**Issue by paszczus** [librenms/librenms#2094]
Please add support for tags like {foreach} or %value.sysName in subject of e-mails

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Is not going to happen before the transport oriented templates and the language remake is done. Otherwise this results in too messy structures.

Please reference this in the ongoing alerting update issue from earlier this year.

Cheers from the trafficjam
F0o


On October 9, 2015 3:30:18 PM GMT+02:00, paszczus <notifications@github.com> wrote:
>Please add support for tags like {foreach} or %value.sysName in subject
>of e-mails
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2094

- --
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJPBAEBCgA5BQJWF8LpMhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikg
PGYwb0BsaWJyZW5tcy5vcmc+AAoJEJMZKtVWOFzB0YgQAIRtL0+nGNfymu6JKldG
ZUlINf4WvASGOTJvXilLp3aid/aJFtKSoSjfH2XX7OedZTbnGZA/rOHeJlPcQ23N
wjTrv2gMRcKEvCtCN0NkBmc/iv8AV6U94T32i/oNqaYdYVbNEGcYvPovssTaXflz
E2brsG1wjb1kAvmq6WIsXD+xsd9FvFhbTW8co4o9waB4Ek38XViaeqCM+Zcpi/QY
4kCz9TPF9IEbgGetiz8g1PisJd3x0NhS1IdaHsdyOzTPLkj9LNw9EwV1nzLPh84F
3i1ETr8HY6hmaYzNFNr/ZRfhWt5q0T9VTqXZPw+2CAg8VT9xS7GC7Oq4eilIsQhR
SVUceopjSK3ADpOKJ6611b/1n/SxshsLZ377uwO6tTxRMbkoISwvdyl9pILlDrB+
fk9/+3RxZSL15InY3Myp6zWBISTR5K6g53U3mJwf2/JUmMG+DZ8CwhpPzl/JD4Es
B9aRJ/iGD4Ecx62+Cw9NARIXzTCuTkkSnEDG5GKuMeMIsHBX+iE3aEoRMhFmwEpO
VsNFwFuK97pkZR0sLjT5v/2BLYz1vVKknNusM53QxItUlJh5T6loa2poLZNxZFh2
D6ilEA3T3oECWomWnXRSvU5wjN13Snu6zVxTbhwCbvZsWlGYm+QSi/wwgDXSwn3W
hK2p0LYPrv/GBDk6XQyzVFVs
=6asQ
-----END PGP SIGNATURE-----

**Comment by laf** [comment]
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by paszczus** [comment]
This one seems to be implemented already
