### ISSUE TITLE
"Error Drawing Graph" for all UCD graphs

### ISSUE THREAD

**Issue by Compizfox** [librenms/librenms#2108]
Hi,

I just switched from Observium to LibreNMS (clean install, no migration). Everything works OK, except for some graphs. It seems that all UCD graphs (load, memory, CPU) are bugged. I get the error "Error Drawing Graph".

I setup 5 devices (some Linux, some FreeBSD) and they all have the same problem.

I already tried enabling the `mib` module (I wasn't sure if I was supposed to) but that doesn't make any difference. The poller doesn't output any errors and the rrd files for the respective graphs exist and have the right permissions.

The host is running Debian.

Thanks in advance.

**Comment by laf** [comment]
@Compizfox As in the graph on the top right of:

https://demo.librenms.org/device/device=19/
u/p: demo

If so, can you provide some info such as what OS the devices are running, version number + net-snmp version number.

**Comment by Compizfox** [comment]
Yes, that is correct. The *storage* graph is working, but the *memory usage* and *processor usage* ones aren't.

![](https://host.tuxplace.nl/screenshots/2015-10-11-21-28-52.png)
![](https://host.tuxplace.nl/screenshots/2015-10-11-21-30-09.png)

The host which is running LibreNMS is running Debian Stretch. I've got multiple other devices (two OpenWRT (Designated Driver) routers, a FreeBSD (10.2-RELEASE) server, a Cisco SPA112 ATA and an ESXi 5.5 hypervisor. All devices have the same problem.

All other graphs are working as they should.

The host is running net-snmp 5.7.3.

**Comment by Compizfox** [comment]
@f0o What info do you need? I'll be glad to help.

**Comment by zetarhopike** [comment]
I had the same problem with a fresh install on Fedora 22. Downgrading the rrdtool package from 1.5.3 to 1.4.9 resolved the issue. The error I received was: RRDTool Output: ERROR: Unused Arguments "" in command : ...

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I think you must specify the rrdtool version if you're over 1.5 because rrdtool has some non-backwardscompatible changes.


On 5 November 2015 16:29:27 CET, CWP <notifications@github.com> wrote:
>I had the same problem with a fresh install on Fedora 22. Downgrading
>the rrdtool package from 1.5.3 to 1.4.9 resolved the issue. The error I
>received was: RRDTool Output: ERROR: Unused Arguments "" in command :
>...
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2108#issuecomment-154093807
-----BEGIN PGP SIGNATURE-----

iQJPBAEBCgA5MhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikgPGYwb0Bs
aWJyZW5tcy5vcmc+BQJWO3cZAAoJEJMZKtVWOFzBzHAQAKILEzQhnYYWz8Slvj0n
2jAstxB0ZB14WF7dvKvpsATjNZBZnTONqgP3PhHjGoDT3zDysjbbyonCFf5ZLykr
CGodZgyJBk6vwPfTT8e4z3BW8XUhmaDmW/Q+KePucavgncaSYNcpBWbW9QqwqoVT
6OkK73hnRt6Xbkz1Wct0Gvj/dziZ0QbSEr0ncAEDbbsjLl5xgOmfg3UNJjaZZ8X/
oXQ/WTyhQ6ogvYfwkdAHHC2l4P6Q5Lr6AgJklujo54QHgZAkp9C1cF/QpkGO1JuL
14U31HeJgiYlUZLvHRAzCpVRrnW4T3Gmc7HI5OVS7M+jVax/90MB2eYI9AbrLr6h
OL5ooUHYj3MuwsH5/4qimHfV+p4m9fWbfhYxbRvV+P2V/8HvM2bwE2YnDIfey82y
7rPdO1VYxD/qA9G3b2Vz+dno7UV9pkmEyTDV/kpONMR3r3lACiiwiuafLxXHT2Zi
bD269MIkEqtJmOeYg1R5CJwJKF58LcFPGfOzDzK5fP53UnAi+r4BkrvQAJ23Vch1
qdLImYPr9Ur1FxdVN9C/h8v8mRwWgHHYUYiVV7HZY/SlqgKRpt8cefDd9PFDLkow
KOCtPCQK+j44BuBXAuGOarNARY4aEMrqRjeOoUY1KPmOlzYgbkBH2c7B0P4uw3HH
HVvAHzdiKieK/v05n3xbYwjf
=gZBi
-----END PGP SIGNATURE-----

**Comment by zetarhopike** [comment]
I tried setting $config['rrdtool_version'] = 1.5; in my config.php and tested with rrdtool 1.5.3 again but the issue returned. Running with rrdtool 1.4.9 is an acceptable solution for my environment for the time being but I'd be happy to do further testing with 1.5.3.

**Comment by Compizfox** [comment]
Can confirm, my machine is running rrdtool 1.5.4.

I tried the same thing (I set `$config['rrdtool_version'] = "1.5.4";`) but that doesn't seem to solve anything.

I'm afraid downgrading rrdtool to an older version is non-trivial with Debian.

**Comment by laf** [comment]
Setting the version won't do anything other than when using rrdcached so don't worry about having to do that.

Compiling rrdtool from source is quite easy.

Otherwise I'll try and take a look at 1.5 tonight.

**Comment by Compizfox** [comment]
> Setting the version won't do anything other than when using rrdcached so don't worry about having to do that.

I see.

> Compiling rrdtool from source is quite easy.

That's not the problem; I know how to compile something from source ;) The problem is that I have other packages installed that depend on rrdtool, so I can't simply remove the package because that will create dependency problems.

**Comment by laf** [comment]
No need to remove. You can compile into another directory and point rrdtool in config.php to the new version.

**Comment by paulgear** [comment]
This is just a bug in how we call the graph; I'll PR up a fix shortly.

**Comment by paulgear** [comment]
Actually, looks like this affects more than just RRDtool 1.5 - here's a UCD diskio graph from my server: http://libertysys.com.au/imagebin/ucd-diskio.png

**Comment by paulgear** [comment]
This seems to be the same root cause as the issues in #2092.  Not sure why the fix was reverted.

**Comment by Compizfox** [comment]
@paulgear: Thanks, https://github.com/librenms/librenms/pull/2430 succesfully fixed the problem.
