### ISSUE TITLE
Ignored Port still alerting

### ISSUE THREAD

**Issue by ubnt-bane** [librenms/librenms#2144]
Interface on DataDomain 2200, veth0, reports 10bps and is alerting due to utilization. I have the port ignored in the device config, but it is still showing on the alert dashboard.

**Comment by laf** [comment]
Looking at the code refreshed my memory on this one.

Because we just run sql queries based on the rules then we don't know your rule is specifically for ports. Ignoring ports is supposed to be done in the rule itself and we have macros to help. So using %macros. port eq 1 will check it's not deleted, ignored or disabled. If you update your rule to use this then it should be ok.

**Comment by laf** [comment]
Feel free to re-open this if you have any further queries.
