### ISSUE TITLE
Poller wrapper timeout

### ISSUE THREAD

**Issue by Alastair-VOIPUNLIMITED** [librenms/librenms#2149]
Hi Team,

Would it be possible to set up a time out for sluggish devices responding to SNMP, for example timing out when poll takes over 300 seconds and the thread moving to next device. (but having duration configurable.)

Thank you.

Alastair

**Comment by laf** [comment]
Hmmm, trying to do it on a per device basis might be hard as what happens if that device starts polling anytime after the first second. If we killed it after 300 seconds then we've already overlapped to the next polling time. If we do it on another value then what about devices that naturally take over that amount of time to poll?

What devices are you having struggle with polling within 300 seconds?

**Comment by Alastair-VOIPUNLIMITED** [comment]
Hi Laf,

Thanks for replying. 

I think this issue is exacerbated when when the device is down on ICMP, the poller still attempts to poll, slowing everything down. This is also the case when there is high packet loss.

We now have a script that kills the thread if it lasts more than 20 mins as a work around for the original issue. 

We have a great number of devices and some not only take a while to poll but also a while to initially respond for the above reason. 

Any advice would be greatly appreciated :)

Kind Regards

Alastair

**Comment by laf** [comment]
Hi @Alastair-VOIPUNLIMITED,

That's odd that the device continues to poll, are you 100% sure? poller.php will carry on for a bit as it will run alerting code and some DB queries but if a device is down for ping for me then it doesn't run all the snmp queries - this is unless you've disabled the icmp check which is now possible but off by default.

If you can post the output for a device that's down:

`./poller.php -h HOSTNAME -d -r`

**Comment by Rosiak** [comment]
Any news on this, otherwise i propose that we close this one.

**Comment by laf** [comment]
Please feel free to comment / re-open.
