### ISSUE TITLE
Services graphs

### ISSUE THREAD

**Issue by gelato** [librenms/librenms#2193]
Graphing of added services via nagios plugins don't work - basically no rrd file is generated under specified hostname folder. I ran tests on ssh service.
Any advices on how to fix it?

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Nothing to fix. This part needs a total recoding and hasnt gotten any updates since the fork.

If you want to, feel free to recode it and PR :)



On October 23, 2015 1:07:55 PM GMT+02:00, gelato <notifications@github.com> wrote:
>Graphing of added services via nagios plugins don't work - basically no
>rrd file is generated under specified hostname folder. I ran tests on
>ssh service.
>Any advices on how to fix it?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2193
-----BEGIN PGP SIGNATURE-----

iQJPBAEBCgA5MhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikgPGYwb0Bs
aWJyZW5tcy5vcmc+BQJWKhVyAAoJEJMZKtVWOFzBhiQQAIV+LRmpYp1UqO0/pqTA
fBvFV4Jkqn+GfpXaLXMEiywf5+CDIEHaacROKaxMmUX+9RYiCOU6NXY42K8whV52
z18xkn1gFTVhDugYRQrZwcmFK7uGaauXPw82sgdYhkOQ8QAHzVDbs11ZiH21FY2O
j/SOECCBJZka/6FXXEKk9eezG/m3GZyX395auYUiO/kD3gWa5q16GNnF25kPFLky
0xp8svuMussD7fKdPM/5TmUWvspZ3J7aVnoebt+WsrdnJaTtjyVMEA63fnLNyQCg
kbrj+XKXvlwYMevVCS3KyzmbvG2pcsR9J++U8na2h64Pr+ze3JWrLPzDJIZ/0TLh
YcCkVvc7WJS4guW6U1wx+7PCcnvSAT/SLrr8oLcK/zrhxFdMKxMmYfh1yq7itTkY
eqKENcw/ttSZerLFwBE3TgYapexHYDj369BrSkDYLw7+hAZvOjMLFkleAU8zqLvN
/IPWyuqPR7BuyNq0R4taHldIpRyJS9nQObFnAAU47Qo1ze0CrXhD26U5KTvSNwWN
lsBcB2rGF3Aly8jrlZ3AiiLnc1jxPLby3SP75JaSdBJ8wAaHe8UoDTCitYoffjp0
ABDpSY73Gkn9pjZ0+P2/n/ozJ56FsdVmG8YMaXmR1YHqJ8n/R9zBwkOnTlmw7nji
kgz+FdjKbdwO463RwsxTEeeK
=gWhz
-----END PGP SIGNATURE-----

**Comment by gelato** [comment]
A pitty to hear that you won't develop this feature (i think this is what you said :) ). If i will have enough time - i'll contribute to this project, but meanwhile the only thing i wrote for services is VNC service check.

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

We will eventually but currently we have more important issues on the list.

This is a community driven project so if the community decides to put more priority on this issue, it will move further up in the list ;)



On October 23, 2015 2:53:06 PM GMT+02:00, gelato <notifications@github.com> wrote:
>A pitty to hear that you won't develop this feature (i think this is
>what you said :) ). If i will have enough time - i'll contribute to
>this project, but meanwhile the only thing i wrote for services is VNC
>service check.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/2193#issuecomment-150562436
-----BEGIN PGP SIGNATURE-----

iQJPBAEBCgA5MhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikgPGYwb0Bs
aWJyZW5tcy5vcmc+BQJWKi4+AAoJEJMZKtVWOFzBtuEP+wc4w0/b6K7OzCdMLuJJ
b2GiWtIlaLqG83mZAqLNS/Vwrpjp0ggbTY4RetB7kklAsty/Eokttrr7ontZBtF8
T/Ap2jgEx9TPSz1V/uC/gmBv/+Sy8Qi+aFipa0QpgLGv+tqSlpNLbWUaasOI/3ND
KjfcE8Z+DvxR0CLrxy51xM61UlWS6YYKd3Nd/2+f/2XAnnbOFHfxv0Gf23q13Bq3
+0MDR9fqvKVXACuk24nrjLFRYXW0pZ69bfrbyQeqAXytop8gXq8HM+6RvzvdV6/b
LckR4TPMkTDJYECUeV/gQcBOSmd2KJVQwfibY5ub7RBmzvvMxtKjZoH7ic++DpZz
GbjgW/0H06tHSNLM9/v90asnWfyMWLWGwSJmWBfQjY+kCfUVYFqEdFtRe9hRSF82
bNRUuvx4UtUMyjvMoD22tRq4+GYlkceSFJ4HDm8e3coqWutCjEFF1tZxJbp5n2NV
yh+Rx431iM0oQK1a51gY7UkG7iUsqj32J7/DkIsynRsHsPho91rJCLFaF2JL7mGE
Xb50RMycAiU5f0jmmrwtFO4HTZgKx+/azyGjv4mQEWMDbfsV2SlZnAANSU+Yo9B+
UxGZ+Nx0nt+tpA4qMA8spO+T+gWMX3hrb7Jzla715Jme3WiU6jV1QdFSHqkP0OEO
xPmqmoWiBKb5EAhDmRsLxvKV
=jyyV
-----END PGP SIGNATURE-----

**Comment by paulgear** [comment]
:+1: This is a good idea, and we could do a lot more with the nagios checks (a.k.a. services) if they were better integrated.  I'll have a look at this when I get a chance.

**Comment by adaniels21487** [comment]
@paulgear, did you get a chance to look at this?
if not, i'll take it on.

**Comment by adaniels21487** [comment]
@paulgear, @f0o, @laf 
Can we close this one team?
