### ISSUE TITLE
similar as $config['uptime_warning'] for other (custom) alerts

### ISSUE THREAD

**Issue by betafork** [librenms/librenms#2367]
ie. Links gone full during the night would show in the morning.

**Comment by laf** [comment]
I'm not sure how we can do this, we don't record the link data for more than 2 polls (current data + previous 5 mins) so we won't be able to show a warning about this.

@librenms/reviewers ?

**Comment by betafork** [comment]
we don't record a device reboot either? 
Maybe just set it as at trigger as an alert option? After a period of time it resets and has to be triggered again?

**Comment by laf** [comment]
device reboot is done via uptime so that's easy as you just alert on anything with an uptime less than 24 hours.

Basing it on alerts also doesn't seem feasible as you are free to create alerts so we don't / won't know which alert to base this one.

I think the best you will get is using the alert history and us providing the ability to filter by date / time.
