### ISSUE TITLE
Feature: Support Manual override of interface speed.

### ISSUE THREAD

**Issue by dragon2611** [librenms/librenms#2377]
Some devices have been known to mis-report the interface speeds, particularly on virtual interfaces such as VPN tunnels and PPP interfaces, this causes problems if interface utilisation alerting is enabled as LibreNMS believes an interface is at high utilisation whilst in reality it isn't.

An example of this would be the UBNT edgerouter reporting PPPoE interfaces at 10M.

**Comment by x3m** [comment]
Hi,

more examples for the same issue are Mikrotik Routers and especially the VPLS tunnels. 

Voting +1 for this feature.

btw, Obs. has it.

**Comment by jcounsell1222** [comment]
+1

this would be quite helpful.

**Comment by jcounsell1222** [comment]
Just out of curiosity is this something that could be implemented quickly? i dont mean to sound pushy or anything so i apologize in advance and appreciate all the work that you do on this product. the issue i am having is that the bandwidth statements that we have implemented can not change due to the affect on routing that it would have. i am not sure if there is a way to do a work around at this time to manually set them at each polling interval.

Thanks in advance for all your time guys.

**Comment by rogersau** [comment]
+1.

Have similar issues with Mikrotik routers

**Comment by masonke** [comment]
+1 Something similar to overriding the location would work.

**Comment by f0o** [comment]
:+1:

**Comment by PaulosV** [comment]
:+1 ! I have some Mikrotik devices in my network and the alerter is suffering from 11Mbps speed on Wifi interface, which is, in reality, something like 300Mbps...

**Comment by seeker-dsr** [comment]
+1 we have microtiks with speed on bonding interfaces set to 10Mpbs

**Comment by Cha0sgr** [comment]
+1 

Same problem here too with MikroTik routers. 

Observium has implemented an override per interface when editing the device's ports properties which is very helpful.  
Any chance we can have this feature on LibreNMS too?  
I'll take a look at the source code first chance I get to see I can make a patch for this.

**Comment by laf** [comment]
Your more than welcome to contribute - please read our contributors agreement first though.

**Comment by Rosiak** [comment]
Merged #3752
