### ISSUE TITLE
Best way to Monitoring Hard drives in RAID Array

### ISSUE THREAD

**Issue by starnetwork** [librenms/librenms#2549]
Hi,
what is the best way to monitor Hard drives in RAID Array
I have branded Dell / HP / IBM servers from many models
I try to Install Dell OpenManage but I see only Temperatures and Fanspeed data
any suggestion?

Regards,

**Comment by laf** [comment]
We should be able to add drive support via Dell OpenManage, can you provide us access to a box to test?

**Comment by starnetwork** [comment]
Hi, it's will take me some time but I will find some box for that tests
anyway, it's required to use OpenManage?
am asking since I don't like it, heavy installation with no big benefit

**Comment by laf** [comment]
I expect you can do it via check_mk / munin plugin I expect.

**Comment by f0o** [comment]
I use munin for my software raids (md-raid) - Perhaps there's something for yours as well?

**Comment by starnetwork** [comment]
Sounds like a good idea,
in general, I have Dell / IBM / HP servers, and in additional to the existing basic monitoring, 2 things:
1. RAID Controller Hard Drives Health - Temperature and any Physical disk failure
2. Server hardware alerts (PS / Mem / CPU / etc...)

how can we promote it?

**Comment by kakopedreros** [comment]
Hi,

in the source code, only exist temp, fanspeed, voltage, it's reading the OpenManage snmp smux.

But in order to get the snmp data for the Storage Management (IDRAC) the oid is:

.1.3.6.1.4.1.674.10893.1

`SNMPv2-SMI::enterprises.674.10893.1.20.1.0 = STRING: "4.4.0"
SNMPv2-SMI::enterprises.674.10893.1.20.2.0 = INTEGER: 3
SNMPv2-SMI::enterprises.674.10893.1.20.3.0 = STRING: "Dell Inc."
SNMPv2-SMI::enterprises.674.10893.1.20.4.0 = STRING: "Server Administrator (Storage Management)"
SNMPv2-SMI::enterprises.674.10893.1.20.5.0 = STRING: "Configuration and monitoring of disk storage devices."
SNMPv2-SMI::enterprises.674.10893.1.20.100.1.0 = STRING: "Server Administrator (Storage Management)"
SNMPv2-SMI::enterprises.674.10893.1.20.100.2.0 = STRING: "Configuration and monitoring of disk storage devices."
SNMPv2-SMI::enterprises.674.10893.1.20.100.3.0 = STRING: "Dell Inc."
SNMPv2-SMI::enterprises.674.10893.1.20.110.3.0 = INTEGER: 1470241872
SNMPv2-SMI::enterprises.674.10893.1.20.110.4.0 = INTEGER: 5
SNMPv2-SMI::enterprises.674.10893.1.20.110.5.0 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.110.6.0 = INTEGER: 300
SNMPv2-SMI::enterprises.674.10893.1.20.110.11.0 = STRING: "4.4"
SNMPv2-SMI::enterprises.674.10893.1.20.110.12.0 = ""
SNMPv2-SMI::enterprises.674.10893.1.20.110.13.0 = INTEGER: 3
SNMPv2-SMI::enterprises.674.10893.1.20.110.14.0 = INTEGER: 3
SNMPv2-SMI::enterprises.674.10893.1.20.110.15.0 = INTEGER: 3
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.1.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.2.1 = STRING: "PERC H200 Integrated"
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.3.1 = STRING: "DELL"
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.4.1 = INTEGER: 6
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.5.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.8.1 = STRING: "07.03.06.00"
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.11.1 = INTEGER: 3
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.12.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.37.1 = INTEGER: 3
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.38.1 = INTEGER: 3
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.39.1 = STRING: "\\0"
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.40.1 = INTEGER: 3
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.41.1 = STRING: "16.00.00.00"
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.42.1 = STRING: "embedded"
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.43.1 = INTEGER: 99
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.47.1 = INTEGER: 2
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.57.1 = INTEGER: 99
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.58.1 = INTEGER: 99
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.59.1 = INTEGER: 99
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.60.1 = INTEGER: 99
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.61.1 = INTEGER: 99
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.62.1 = INTEGER: 9999
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.63.1 = INTEGER: 99
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.64.1 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.65.1 = INTEGER: 99
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.66.1 = INTEGER: 99
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.67.1 = STRING: "9999"
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.68.1 = INTEGER: 9999
SNMPv2-SMI::enterprises.674.10893.1.20.130.1.1.69.1 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.2.1.1.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.130.2.1.1.2 = INTEGER: 2
SNMPv2-SMI::enterprises.674.10893.1.20.130.2.1.2.1 = STRING: "Connector 0"
SNMPv2-SMI::enterprises.674.10893.1.20.130.2.1.2.2 = STRING: "Connector 1"
SNMPv2-SMI::enterprises.674.10893.1.20.130.2.1.3.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.130.2.1.3.2 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.130.2.1.7.1 = INTEGER: 3
SNMPv2-SMI::enterprises.674.10893.1.20.130.2.1.7.2 = INTEGER: 3
SNMPv2-SMI::enterprises.674.10893.1.20.130.2.1.8.1 = INTEGER: 3
SNMPv2-SMI::enterprises.674.10893.1.20.130.2.1.8.2 = INTEGER: 3
SNMPv2-SMI::enterprises.674.10893.1.20.130.2.1.9.1 = STRING: "\\0\\0"
SNMPv2-SMI::enterprises.674.10893.1.20.130.2.1.9.2 = STRING: "\\0\\1"
SNMPv2-SMI::enterprises.674.10893.1.20.130.2.1.11.1 = INTEGER: 8
SNMPv2-SMI::enterprises.674.10893.1.20.130.2.1.11.2 = INTEGER: 8
SNMPv2-SMI::enterprises.674.10893.1.20.130.3.1.1.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.130.3.1.2.1 = STRING: "Backplane"
SNMPv2-SMI::enterprises.674.10893.1.20.130.3.1.3.1 = STRING: "DELL"
SNMPv2-SMI::enterprises.674.10893.1.20.130.3.1.4.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.130.3.1.6.1 = STRING: "0:0"
SNMPv2-SMI::enterprises.674.10893.1.20.130.3.1.8.1 = STRING: "0"
SNMPv2-SMI::enterprises.674.10893.1.20.130.3.1.12.1 = STRING: "BACKPLANE       "
SNMPv2-SMI::enterprises.674.10893.1.20.130.3.1.16.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.130.3.1.19.1 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.3.1.23.1 = INTEGER: 3
SNMPv2-SMI::enterprises.674.10893.1.20.130.3.1.24.1 = INTEGER: 3
SNMPv2-SMI::enterprises.674.10893.1.20.130.3.1.25.1 = STRING: "\\0\\0\\0"
SNMPv2-SMI::enterprises.674.10893.1.20.130.3.1.26.1 = STRING: "1.07"
SNMPv2-SMI::enterprises.674.10893.1.20.130.3.1.30.1 = STRING: "5882B0B039A0BC00"
SNMPv2-SMI::enterprises.674.10893.1.20.130.3.1.31.1 = INTEGER: 9999
SNMPv2-SMI::enterprises.674.10893.1.20.130.3.1.32.1 = INTEGER: 9999
SNMPv2-SMI::enterprises.674.10893.1.20.130.3.1.33.1 = INTEGER: 9999
SNMPv2-SMI::enterprises.674.10893.1.20.130.3.1.34.1 = STRING: "2434178835"
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.1.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.1.2 = INTEGER: 2
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.2.1 = STRING: "Physical Disk 0:0:1"
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.2.2 = STRING: "Physical Disk 0:0:0"
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.3.1 = STRING: "DELL(tm)"
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.3.2 = STRING: "DELL(tm)"
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.4.1 = INTEGER: 3
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.4.2 = INTEGER: 3
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.6.1 = STRING: "TOSHIBA MK1661GSYB"
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.6.2 = STRING: "TOSHIBA MK1661GSYB"
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.7.1 = STRING: "41CFT24JT"
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.7.2 = STRING: "41CFT24IT"
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.8.1 = STRING: "ME0D"
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.8.2 = STRING: "ME0D"
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.9.1 = STRING: "0"
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.9.2 = STRING: "0"
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.10.1 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.10.2 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.11.1 = INTEGER: 152064
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.11.2 = INTEGER: 152064
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.12.1 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.12.2 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.13.1 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.13.2 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.14.1 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.14.2 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.15.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.15.2 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.16.1 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.16.2 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.17.1 = INTEGER: 152064
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.17.2 = INTEGER: 152064
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.18.1 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.18.2 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.19.1 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.19.2 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.20.1 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.20.2 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.21.1 = INTEGER: 7
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.21.2 = INTEGER: 7
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.22.1 = INTEGER: 5
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.22.2 = INTEGER: 5
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.23.1 = INTEGER: 3
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.23.2 = INTEGER: 3
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.24.1 = INTEGER: 3
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.24.2 = INTEGER: 3
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.26.1 = STRING: "\\0\\0\\0\\1"
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.26.2 = STRING: "\\0\\0\\0\\0"
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.27.1 = STRING: "PH0P2XD22640214C037DA00"
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.27.2 = STRING: "PH0P2XD22640214C037CA00"
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.28.1 = STRING: "4433221106000000"
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.28.2 = STRING: "4433221107000000"
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.29.1 = INTEGER: 3072
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.29.2 = INTEGER: 3072
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.31.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.31.2 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.35.1 = INTEGER: 2
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.35.2 = INTEGER: 2
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.36.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.36.2 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.40.1 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.40.2 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.41.1 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.41.2 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.42.1 = INTEGER: 99
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.42.2 = INTEGER: 99
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.49.1 = STRING: "Not Applicable"
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.49.2 = STRING: "Not Applicable"
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.50.1 = INTEGER: 512
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.50.2 = INTEGER: 512
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.51.1 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.4.1.51.2 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.130.5.1.1.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.130.5.1.1.2 = INTEGER: 2
SNMPv2-SMI::enterprises.674.10893.1.20.130.5.1.2.1 = STRING: "Physical Disk 0:0:1"
SNMPv2-SMI::enterprises.674.10893.1.20.130.5.1.2.2 = STRING: "Physical Disk 0:0:0"
SNMPv2-SMI::enterprises.674.10893.1.20.130.5.1.3.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.130.5.1.3.2 = INTEGER: 2
SNMPv2-SMI::enterprises.674.10893.1.20.130.5.1.4.1 = STRING: "Backplane"
SNMPv2-SMI::enterprises.674.10893.1.20.130.5.1.4.2 = STRING: "Backplane"
SNMPv2-SMI::enterprises.674.10893.1.20.130.5.1.5.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.130.5.1.5.2 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.130.5.1.6.1 = STRING: "PERC H200 Integrated"
SNMPv2-SMI::enterprises.674.10893.1.20.130.5.1.6.2 = STRING: "PERC H200 Integrated"
SNMPv2-SMI::enterprises.674.10893.1.20.130.5.1.7.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.130.5.1.7.2 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.140.1.1.1.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.140.1.1.2.1 = STRING: "Virtual Disk 0"
SNMPv2-SMI::enterprises.674.10893.1.20.140.1.1.3.1 = STRING: "/dev/sda"
SNMPv2-SMI::enterprises.674.10893.1.20.140.1.1.4.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.140.1.1.6.1 = INTEGER: 152064
SNMPv2-SMI::enterprises.674.10893.1.20.140.1.1.7.1 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.140.1.1.12.1 = INTEGER: 99
SNMPv2-SMI::enterprises.674.10893.1.20.140.1.1.13.1 = INTEGER: 3
SNMPv2-SMI::enterprises.674.10893.1.20.140.1.1.14.1 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.140.1.1.15.1 = INTEGER: 65536
SNMPv2-SMI::enterprises.674.10893.1.20.140.1.1.17.1 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.140.1.1.19.1 = INTEGER: 3
SNMPv2-SMI::enterprises.674.10893.1.20.140.1.1.20.1 = INTEGER: 3
SNMPv2-SMI::enterprises.674.10893.1.20.140.1.1.21.1 = STRING: "\\0\\0"
SNMPv2-SMI::enterprises.674.10893.1.20.140.1.1.22.1 = INTEGER: 2
SNMPv2-SMI::enterprises.674.10893.1.20.140.1.1.23.1 = INTEGER: 2
SNMPv2-SMI::enterprises.674.10893.1.20.140.1.1.24.1 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.140.1.1.25.1 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.140.1.1.26.1 = INTEGER: 2
SNMPv2-SMI::enterprises.674.10893.1.20.140.1.1.27.1 = INTEGER: 99
SNMPv2-SMI::enterprises.674.10893.1.20.140.1.1.28.1 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10893.1.20.140.3.1.1.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.140.3.1.1.2 = INTEGER: 2
SNMPv2-SMI::enterprises.674.10893.1.20.140.3.1.2.1 = STRING: "Physical Disk 0:0:1"
SNMPv2-SMI::enterprises.674.10893.1.20.140.3.1.2.2 = STRING: "Physical Disk 0:0:0"
SNMPv2-SMI::enterprises.674.10893.1.20.140.3.1.3.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.140.3.1.3.2 = INTEGER: 2
SNMPv2-SMI::enterprises.674.10893.1.20.140.3.1.4.1 = STRING: "Virtual Disk 0"
SNMPv2-SMI::enterprises.674.10893.1.20.140.3.1.4.2 = STRING: "Virtual Disk 0"
SNMPv2-SMI::enterprises.674.10893.1.20.140.3.1.5.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10893.1.20.140.3.1.5.2 = INTEGER: 1
`

**Comment by reliam** [comment]
Do you guys still need access?

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-monitor-hard-drives-in-raid-array/730
