### ISSUE TITLE
Discoverying and polling VRF, OSPF and BGP Processes on Nexus 7K : where to start coding

### ISSUE THREAD

**Issue by htam-net** [librenms/librenms#280]
Hi,

I would like to give a try to code some PHP Patchs, so that LibreNMS can discover VRF, OSPF, BGP and so on Nexus 7K platform (our reference will be Nexus 7700 with NX-OS 6.2).

We are implementing "VRF-Lite" style (no MPLS), so according to Cisco documentation, it is mandatory to map in NX-OS configuration, a SNMP Context (v3) to each instance of VRF, OSPF, BGP, whatever ....

My try will be to first discover the context mapping with this Cisco MIB : CISCO-CONTEXT-MAPPING-MIB.my

and then to iterate on these mappings using an additional function like "get snmp walk/bulk with context" on these contexts.

Do you have any advice how I could do that ?
Which files should I implement / pacth ?
Which files could I use as examples and inspiration ?

Thank you in advance for your help,
Sincerely yours, Mathieu.

**Comment by HenocKA** [comment]
Hey @htam-net @laf !
No news about this feature-request ?

**Comment by nicearma** [comment]
Hello @HenocKA, this feature was implement in my libreNMS fork, because i changed of work i didn't have the time to make the all changes order by the community and test it. Normally someone of my old job is working on it (maybe is you). I don’t think i will work with this code anymore, because i didn't like how i ended it with them (is not the enterprise who ask me to do this, the problem is with the IT consulting enterprise who send me to them).  IT consulting ->SSI in french.

Anyone can take the code and work on it, i will put this information in the fork for help any other to take and work with the code (htma-net have the same right of me in the code, so he can fork and give you any right to).

**Comment by HenocKA** [comment]
Yes, it's me and i am working on it. I just want to know if anybody else
was working on it.
Thanks Nicolas.

Le dim. 29 nov. 2015 à 18:11, Nicolas Armando <notifications@github.com> a
écrit :

**Comment by laf** [comment]
I believe this is now all done.
