### ISSUE TITLE
Issues with adding Cisco NX-OS switch on LibreNMS

### ISSUE THREAD

**Issue by breeman1** [librenms/librenms#2872]
Hello,

I am trying to add Cisco MDS 9148 switch on our production deployment of LibreNMS and I am facing these issues;
1. The switch can be added on the command line and polled successfully with snmp v2 however it does not display Mempools stats.
2. With snmp v3 enabled on the switch cannot be added via the cli but only via the GUI. See below,
![image](https://cloud.githubusercontent.com/assets/16717388/12614815/daf8cd98-c50a-11e5-8f63-3e946b126db6.png)

![image](https://cloud.githubusercontent.com/assets/16717388/12615296/8cd66b36-c50d-11e5-8de3-75cf638e2368.png)
1. When the  switch with snmpv3 the it also does not display CPU Usage stats over and above the Mempools. See below,

![image](https://cloud.githubusercontent.com/assets/16717388/12615481/9c4c69f2-c50e-11e5-8b24-80c6c61b859b.png)

![image](https://cloud.githubusercontent.com/assets/16717388/12615483/a395fb74-c50e-11e5-938e-0aa91cfad8e9.png)

**Comment by laf** [comment]
When adding via CLI please just do ./addhost.php rather than php addhost.php

However that's basically doing the same thing as the webui so I can only assume it's because of that.

As for mempool issue, please run:

./discovery.php -h HOSTNAME -d -m mempools
./poller.php -h HOSTNAME -d -r -f -m mempools

For the processor issue:

./discovery.php -h HOSTNAME -d -m processors
./poller.php -h HOSTNAME -d -r -f -m processors

post outputs onto dpaste.de

**Comment by breeman1** [comment]
Hi laf,

Any news on the attached information you requested?

**Comment by laf** [comment]
Not yet, please be patient. All time spent here is done in my spare time.

**Comment by breeman1** [comment]
Take the time you need:). Just thought you missed my earlier response.

**Comment by murrant** [comment]
The pastes expired, please re-post them with no expiration.  Thanks.

**Comment by breeman1** [comment]
Hi @murrant 

Please see here in sequence;
for mempool:
http://pastebin.com/Retr345v
http://pastebin.com/XWXqNSCX

For processor:
http://pastebin.com/mPLFFLAf
http://pastebin.com/9J0WDpdc

**Comment by breeman1** [comment]
Fixed by pull #4825
