### ISSUE TITLE
memory graph trending up on ubuntu linux

### ISSUE THREAD

**Issue by breeman1** [librenms/librenms#2906]
I have LibreNMS running on ubuntu linux 14.04 box which itself is monitored by LibreNMS. I have noticed the the memoru utilsation graph is trending up for no reason that I can pick up. Is anyone experiencing this or is it normal behaviour? Where should I look to solve this issue?

I have restarted the box several time but as you can see from the graph below keep the memory graphs trending up all the time.

![image](https://cloud.githubusercontent.com/assets/16717388/12717618/ae4f46f6-c8f1-11e5-890e-dc5e15ee4e1a.png)

**Comment by paulgear** [comment]
This is perfectly normal behaviour.  In fact, I'm surprised that a) memory usage is not 100%, and b) that it drops down as far as it does.

You should not reboot your box because of this.  All half-decent operating systems will use all of the memory you give them unless they are dramatically under-utilised (as this one seems to be).

For a better understanding of your LibreNMS server's memory usage, go to /graphs/device=1/type=device_ucd_memory/legend=yes/ on your LibreNMS install.
