### ISSUE TITLE
Alert for in/out pps

### ISSUE THREAD

**Issue by blackmetal1** [librenms/librenms#3004]
Hello,
can anyone send rule for in/out pps alert if more than 10000 pps receive or send then alert and email it for network admin?
thanks,

**Comment by laf** [comment]
You probably want ifInUcastPkts_delta and ifOutUcastPkts_delta so you can either do that in the webui for each direction or create a macro and use it for both. For the macro do:

```php
$config['alert']['macros']['rule']['pps_check'] = '(%ports.ifInUcastPkts_delta || %ports.ifOutUcastPkts_delta)';
```

^^ untested

Then for entity use macros.pps_check, Condition larger than or equals and value = 10000. Please also add another entity check for macros.port_up equals 1 so that this only works for valid ports that are currently up.

**Comment by blackmetal1** [comment]
Hello,
i have another issue when i go to create rule and add new rule it says
An error occurred creating this alert.
but rule will show in rules list,
and also when i choose my device go to edit section and go to alerts tab for create new rule for specific device it says An error occurred creating this alert. and no rules will add,
how cna i check it? what is the issue?
thanks,

**Comment by blackmetal1** [comment]
and also in addition to my previous reply i use your macros but when i receive email for this alert it is as likeas following : 
Alert for device xxxxxxx - Sensor under limit
Severity: critical
Timestamp: x
Unique-ID: x
Rule: PPS Check
Faults:
  #1: port_id => 20; ifDescr => Vlan1000;
  #2: port_id => 30; ifDescr => Vlan1091;


it does not show how much pps is, hwo can i solve this?
thanks

**Comment by f0o** [comment]
1) We will look into the error.
2) alerts tab under devices will be removed soon, dont use it. Use the alert-mapping instead.
3) you can create your own alert template to display desired information in your mail/... - consult the docs regarding alerting for this please

**Comment by laf** [comment]
All of this should be resolved now.
