### ISSUE TITLE
Legacy HP ILO code?

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenms#3107]
includes/discovery/sensors/temperatures/hpilo.inc.php

Remove? I see no reason to iterate through this every time sensor disco is run.

**Comment by murrant** [comment]
I'll try adding an ilo and see if it works.  I thought it discovered everytime because it was trying to associate it with a device, but looking at the code, I don't think that is the case.

At the very least it should probably have os discovery set up and a test added to the hpilo temperatures file.

**Comment by murrant** [comment]
Hmm, interesting, apparently ilo 1,2,3 only have pass-through snmp to the host os.  It may be different with ilo4, but I doubt this code supports that.

I am leaning towards delete.

**Comment by murrant** [comment]
@zarya  thoughts?

**Comment by laf** [comment]
if it's used by people I'm not sure why we'd delete it.

Do we not have anything we can check against before running the snmp command?

**Comment by zarya** [comment]
It works of the pass-through to the host running the snmpagent if i remember correct.

**Comment by pheinrichs** [comment]
Ran into an issue with this when trying to add cambium support. I created a temp sensor for some cambium devices but not all the devices have a temperature sensor. So when the condition didn't pass it failed over to this.
