### ISSUE TITLE
Device performance graph broken

### ISSUE THREAD

**Issue by vitalisator** [librenms/librenms#3114]
on some devices the performance graph look like this:
http://imgur.com/n4wfk8o

SQL Data seems to be ok:
http://imgur.com/B3h67TM

in some cases the graph data become ok when I choose a bigger time range.
Have seen this issue since some days ago. Anything changed here?

ideas what could be broken?

**Comment by adammmmm** [comment]
Same here, same issue on every device we have.

**Comment by laf** [comment]
I've actually proposed we remove this feature and table due to shear volume of data it generates. MySQL just isn't designed for it.

**Comment by vitalisator** [comment]
@laf what is the replacement for that?

**Comment by laf** [comment]
No replacement it's just the current feature is a burden on MySQL and one of the causes for using up all innodb buffers. It's a good theory but doesn't work in practice.

**Comment by ekoyle** [comment]
Would it be better to move the data to rrd's?

**Comment by paulgear** [comment]
@ekoyle @vitalisator Ping data is present in RRD form at http://YOUR-LIBRENMS/graphs/type=device_ping_perf/device=YOUR_DEVICE/

**Comment by ekoyle** [comment]
I was thinking of perf_times rather than device_perf.  Is there any chance
someone would want to alert on this?  If so, we should keep the most recent
result in the db; otherwise I agree that we should just drop the table,
especially since the data is already in an rrd.

I think we should consider the same treatment for perf_times (keep most
recent in db, put the rest into rrds iff someone wants the historical data).

**Comment by paulgear** [comment]
We could easily add the latest times to MySQL.  I had planned to do this in a future version of data_update() (in includes/datastore.inc.php).  Alerting based on a ping (or poller) time over a particular threshold is certainly a useful feature that we should keep.

**Comment by laf** [comment]
This issue was fixed a bit ago, closing.
