### ISSUE TITLE
Linux - Memory usage confusion on Front page.

### ISSUE THREAD

**Issue by eikik87** [librenms/librenms#3179]
Firstly, I'm not the biggest linux know how man. But I always thought there was something wrong with my librenms server ( Ubuntu ). Cause it kept showing 95% - 100% physical memory usage. But behind in the shadow of librenms, I can see that it is just the cached memory being used in the RAM. Like Linux machines do, they use the RAM in a smart way. But I didn't know that. But maybe there is a way to display this is more decent way if it is Linux machine. Instead of showing Physical. It would show information more useful to alarm admins if there is something wrong. 

![image](https://cloud.githubusercontent.com/assets/13901674/13570461/413aea94-e466-11e5-81ae-b935bf0924a1.png)

**Comment by murrant** [comment]
Hmm, this would be a different graph I think.  I know what I would call "free" memory: "Available Memory", but what would you call the "used" memory to make it clear?

**Comment by geordish** [comment]
I was talking to @eikik87 regarding this issue on IRC, and I agree with him.

The data is already collected, and displayed in a different graph.

![graph](https://cloud.githubusercontent.com/assets/1226821/13575648/eabc9f48-e481-11e5-8df8-344ef26a38ac.png)

I believe what should actually be displayed as available is the second line marked as - Sh, Bu, Ca.

**Comment by paulgear** [comment]
I think it would be a bad idea to change these graphs to indicate something other than what the SNMP data is returning.  That is one of the key principles we work from - unless the data is clearly wrong and can't be fixed at the source, we shouldn't mess with it.

With respect to Linux memory usage, not all of the memory marked as shared, buffers, and cache is available.  e.g. Sometimes memory is shared because there are multiple copies of an executable running and they can share identical code pages.  A certain minimal number of buffers & cache is necessary for reasonable I/O performance also.

The answer to misunderstanding the relationship of the different memory figures is education, not changing the graph.

**Comment by murrant** [comment]
I agree with @paulgear on this one.

**Comment by f0o** [comment]
Agree with @paulgear

**Comment by laf** [comment]
Please feel free to re-open / comment
