### ISSUE TITLE
HELP : Hot to read interface error graphs

### ISSUE THREAD

**Issue by mail3dexter** [librenms/librenms#3284]
Hello guys,

I am a bit confused on how to read interface error graphs.

Here is one of the graphs which I was trying to figure out : http://prntscr.com/ajbseg

Legend states that it is packets/sec and graphs shows its Xm . What does that m stands for?

Shouldn't it be number of errors in count/units?

Thanks,
Mayur

**Comment by f0o** [comment]
The graphs show the rate of given metric in using SI prefixed units.
100m becomes 100 milli
100M however is 100 mega

On 24 March 2016 12:30:53 CET, Mayur Patel <notifications@github.com> wrote:
>Hello guys,
>
>I am a bit confused on how to read interface error graphs.
>
>Here is one of the graphs which I was trying to figure out :
>http://prntscr.com/ajbseg
>
>Legend states that it is packets/sec and graphs shows its Xm . What
>does that m stands for?
>
>Shouldn't it be number of errors in count/units?
>
>Thanks,
>Mayur
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/issues/3284

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cjon-nexcess** [comment]
This answer makes no sense.  An interface cannot have 6.18 milliErrors.  Errors are an integer value.

I have an interface that had 1 FCS input error over a 5 minute period (this datum was obtained by running a script to capture the `show interface` command every 5 minutes on the 5 minute boundary).  It had no other errors for the 10 minutes before and after the 5 minute period.  It passes around 55Kpps, so 5 minutes is ~16.5Mpkts and the number of packets was actually 16,679,540 over that 5 minute period.  My graphs showed 6.18m for the 5 minute period that the error occured in and 484.01u for the 5 minute period after it (in which no errors occurred). I can not see any way in with this related to the actual number of errors.

**Comment by paulgear** [comment]
@cjon-nexcess The figures you're seeing make perfect sense, because they are not counters (number of errors), but rates (number of errors per second).  RRDtool automatically displays milli and micro for all units.  So 1 error in 5 minutes during which time there were 16.5M packets is 1 / ( 16,679,540 / 300 ) = 1 / 55598.466666667 = 0.000017986 errors / second, or 0.017986 millierrors / second, or 17.986 microerrors per second.

The number 6.18 millierrors doesn't make a lot of sense if it exactly corresponds to that timeslot, but a show interface command every 5 minutes would almost certainly not overlap exactly with the LibreNMS poller, so the results would be different depending on the packet rates before & after the overlap.
