### ISSUE TITLE
RRD size configurable?

### ISSUE THREAD

**Issue by FezzFest** [librenms/librenms#3490]
Is there an option in the LibreNMS configuration to set the maximum disk usage for the RRD graphs? 
According to #2181 "rrd is fixed size", but I recently had to reinstall a VM after the /opt/librenms/rrd folder had grown to 16+GB and disk usage showed 100% usage.

**Comment by laf** [comment]
No you can't do that unless you choose not to store 2 years of historical data which we don't provide an option for.

RRD is fixed size but as you add more devices / ports or we add more support for things then disk usage will increase but not considerably

Here's the graph of our rrdcached box which shows overtime how it's growing in size - for us that's because we're adding devices all the time:

![image](https://cloud.githubusercontent.com/assets/3941142/15015144/08b96686-1202-11e6-9a74-0ee21f12de1c.png)
