### ISSUE TITLE
Monitoring Dell PERC Arrays Health

### ISSUE THREAD

**Issue by gadago** [librenms/librenms#361]
Hi,

This is a feature request to have the ability to monitor the health of arrays on Dell PERC/LSI controllers.

I believe the sensor data can be obtained from Dell OpenManage/IPMI.

In particular, it would be great if this could be supported on Dell  11th and 12th generation server with PERC H200 or H700 controller or newer.

Thanks,

**Comment by laf** [comment]
Hopefully PR referenced above will provide this. It uses virtualDiskState which uses this for values:

The current condition of this virtual disk
(which includes any member array disks.)
Possible states:
0:Unknown
1:Ready - The disk is accessible and has no known problems.
2:Failed - Access has been lost to the data or is about to be lost.
3:Online
4:Offline - The disk is not accessible. The disk may be corrupted or intermittently unavailable.
6:Degraded - The data on the virtual disk is no longer fault tolerant because one of the underlying disks is not online.
15:Resynching
16:Regenerating
24:Rebuilding
26:Formatting
32:Reconstructing
35:Initializing
36:Background Initialization
38:Resynching Paused
52:Permanently Degraded
54:Degraded Redundancy

Once this is merged, if it doesn't fix provide what you need then please feel free to re-open this and provide more info.
