### ISSUE TITLE
Need a method for deleting maintenance windows 

### ISSUE THREAD

**Issue by budbach** [librenms/librenms#3714]
Currently, when a maintenance window lapses, there is no way to delete it.

Ideally, there would be a delete button next to the "Lapsed" indicator on the GUI to delete lapsed maintenance windows.  Just thinking about it, it might be nice to have an edit button too so you can edit a previously lapsed maintenance window so that it would become active again (i.e. change the times).  This would cover the use case where maintenance was scheduled but either did not get completed or was rescheduled.

**Comment by laf** [comment]
I've just closed the PR that was done for this. At present we haven't really concluded if this should be something that is added.

We welcome a discussion though

**Comment by laf** [comment]
No further feedback provided. Feel free to comment and we will re-open

**Comment by YenzRanger** [comment]
That's a feature I'd like to see implented as well.

Both the edit and the delete action would be useful.

We scheduled a maintenance but we weren't finished at the end and because editing was not possible we added a new entry to kind of "extend" the other entry.

Deleting entries is just for cleaning purposes. In general I would leave the entries in there for ducmentation purposes. But from time to time you may have some rows you want to get rid of.
