### ISSUE TITLE
nfSen Integration Issue

### ISSUE THREAD

**Issue by wwardcollective** [librenms/librenms#3720]
I have not been able to get the nfSen rrds to be accepted by LibreNMS and I have found no other working examples except for the documentation. Below is a literal example of what I have in the configuration (minus the domain):

$config['rrdcached']    = "unix:/var/rrdtool/rrdcached/rrdcached.sock";
...
// NfSen functions
$config['nfsen_enable'] = 1;
$config['nfsen_split_char']   = "_";
$config['nfsen_rrds']   = "/opt/librenms/rrd/nfsen/";
#$config['nfsen_suffix']   = array('oobmgmt_ewr004_example_net','ewr004_example_net','dc3_example_net','sv4_example_net');
#$config['nfsen_suffix']   = "";
#$config['nfsen_suffix']   = "_example_net";
#$config['nfsen_suffix']   = "_oobmgmt_ewr004_example_net";

The rrdcached line was included and I have tried all of this with or without rrdcached and suffix options and met with failure. Also, I have tried with each variation of suffix options. I left them commented to remind myself of what I have tried.

Please, help.

P.S. - Forgot to add a practical example of an RRD file:

switch1a_oobmgmt_ewr004_example_net.rrd

**Comment by worton** [comment]
If you look in html/pages/device.inc.php you can find the code where it tries to convert librenms device hostname to a nfsen rrd file. It does this in three steps on the hostname:
1- regex replace any "." with the nfsen_split_char
2- strstr to strip off the nfsen_suffix from the end
3- add $config['nfsen_rrds'] the the beginning and ".rrd" to the end

Since you seem to be saying that your nfsen rrd files have your domain name (_example_net), I think your nfsen_suffix should = "". But you tried that.

Are your nfsen RRD files really in /opt/librenms/... ? That seems weird that your nfsen install would be storing data inside of your librenms install. Mine are in /opt/nfsen/profiles-stat/live, which is only a slight variation from the librenms default of $config['nfsen_rrds']   = "/var/nfsen/profiles-stat/live/"

**Comment by wwardcollective** [comment]
Sorry it took me so long to respond. Everything that you stated should have been the case but nothing worked. After not looking at this for one month (vacation and shifted priorities), I logged in to see the issue was fixed.

Being that I do have nightly upgrades enabled, I would have to spend some time looking at 'git blame' and whatever else to see what in the code fixed it...not planning on doing that.

![screenshot from 2016-08-08 15-18-10](https://cloud.githubusercontent.com/assets/13353930/17492881/dc4b39a6-5d7b-11e6-80d2-2e67e574e67e.png)
