### ISSUE TITLE
Recent change broke Network Map 

### ISSUE THREAD

**Issue by spinza** [librenms/librenms#3793]
A recent change has broken something with network map functionality.  Must have happened in the last 2 weeks or so.

My network map has almost completely disappeared.  AFAIK it was using port ARP information to draw the map but now it seems to only include devices that are down.  ARP information for up devices are still present on the ports.

**Comment by spinza** [comment]
Could be one of these:

* #3733 
* #3715 
* Maybe even #3602

**Comment by mwen** [comment]
After last night's daily update I noticed the same thing happen. All interfaces suddenly became NULL, and the network map also disappeared. It turns out that commit debe052f56ed43d62c09485f35f3822c8dfcae7c fixed the problem for me after manually executing daily.sh, then the poller started filling up everything as it was before. The network map now works again as well.

**Comment by spinza** [comment]
Thanks, I see that's in this PR #3790 
Was wondering whether that might be related.  Will test later to see if it resolves it.

**Comment by spinza** [comment]
Confirmed it seems to be fixed (by #3790 ?)
