### ISSUE TITLE
Syslog catch-call

### ISSUE THREAD

**Issue by XxPatrickxX** [librenms/librenms#381]
Add in the capacity to log syslog entries which fail to match an existing host entry.

**Comment by laf** [comment]
Just got round to looking into this.

So it's possible to add a config option to allow for unmatched hosts against the DB, however the issue after this is that the OS of the device is used to pattern match the message and manipulate it. This is something that wouldn't be able to be done anymore.

It could be a case of just dump unmatched entries and leave it upto the end user to decipher things but that's not the design goal :)

@paulgear or @f0o any thoughts?

**Comment by f0o** [comment]
I would like to invest little more effort in this feature and make it device-id agnostic.

Leaving the identification solely to the Source-IP of the message.

My plan would be to make the syslog-parser accept any messages and add those into the DB using Source-IP as `device_id` replacement.
We will still benefit from pre-parsed syslog messages because they wont require a `device_id` to be present, it's all regex anyhow - no OS checks... 
I would still try to map Source-IP to device_id to create overlibs & device-page entries - but I wouldnt require it anymore.

I should be able to file a PR for above mentioned changes by next monday.

Optionally/Additionally I can take a look at the DB-Format of other syslog search applications to make it compatible with those engines. (if you'd like this, name me some)

**Comment by laf** [comment]
The regex is based on the OS though, different regex for different OS'. I suppose you can probably check each regex would match before running it?

**Comment by f0o** [comment]
That was the plan :)

**Comment by f0o** [comment]
Can somebody give me an excerpt of Cisco's IOS syslog messages so I can figure a format?

**Comment by laf** [comment]
I'll grab some now. They can vary though based on some options selected.

**Comment by laf** [comment]
With:

service timestamps debug datetime localtime show-timezone
service timestamps log datetime localtime show-timezone

Jan 24 11:00:48 GMT: %SEC-6-IPACCESSLOGP: list Vty_Access denied tcp 23.25.167.30(51102) -> 0.0.0.0(22), 1 packet
Jan 24 12:04:09 GMT: %SEC-6-IPACCESSLOGP: list Vty_Access denied tcp 190.57.200.240(37998) -> 0.0.0.0(22), 1 packet
Jan 24 12:25:26 GMT: %SEC-6-IPACCESSLOGP: list Vty_Access denied tcp 106.112.188.255(10311) -> 0.0.0.0(22), 1 packet
Jan 24 13:33:56 GMT: %SEC-6-IPACCESSLOGP: list Vty_Access denied tcp 112.116.246.231(16996) -> 0.0.0.0(22), 1 packet
Jan 24 13:36:37 GMT: %SEC-6-IPACCESSLOGP: list Vty_Access denied tcp 117.9.234.222(15152) -> 0.0.0.0(22), 1 packet

Without:

%SYS-5-CONFIG_I: Configured from console by user on vty0 (1.1.1.1)

**Comment by f0o** [comment]
Thanks!

**Comment by f0o** [comment]
Ok I give up :/

I've prototyped 4 different approaches and none satisfies my standards.

Would an integration of graylog2 be ok?

**Comment by laf** [comment]
Totally forgot to respond to this @f0o :(

I don't know graylog2 but is it not a bit overkill for people to install to get syslog data in?

Maybe being able to integrate into an separate graylog2/elk system might be handy (we use elk at work so correlating the data between the two would be awesome).

Otherwise maybe taking this back to a more basic level of if the hostname doesn't match then dump the data raw into syslog and we can just update the web ui for people to browse through that data?

**Comment by f0o** [comment]
Yes the integration of graylog/elk/tobediscussed would be as addition to the current syslog.

As result I wouldnt make any changes to allow unknown devices to feed messages into librenms' syslog.
Guessing the OS from the format of messages generates too many false-positives and thus creates confusing facilities,categories & cmds - resulting in a fairly unuseable/searchable syslog-overview :/

Open for suggestions

**Comment by XxPatrickxX** [comment]
To prevent scope creep for the original issue. How about having it dump out to /tmp the raw output anything not matched against the devices already in the system and then trim it daily? Toggle enable the "feature" via a config option.

Down the road, integration of a third party syslog analysis package is an interesting idea at the very least.

**Comment by laf** [comment]
Syslog messages could get quite large so dumping to disk might not be suitable.

In my mind I was only thinking about dumping the entire syslog line into the msg column.

**Comment by laf** [comment]
We now have graylog2 support which allows you to view all logs rather than just what is matched.
