### ISSUE TITLE
Bug in alert template variable parsing

### ISSUE THREAD

**Issue by florianbeer** [librenms/librenms#3993]
Given the following template for a sensor with upper limit 50 and lower limit 20
```
Limit: %value.sensor_limit / %value.sensor_limit_low
```
will result in the following parsed output:
```
Limit: 50 / 50_low
```
should return:
```
Limit: 50 / 20
```

**Comment by laf** [comment]
I've had a look at this and it looks tricky to fix in the code ( @f0o - any suggestions).

The reason for it is we replace sensor_limit to format for the template, because sensor_limit_low contains sensor_limit then it's mis-replaced.

However......a work around is to do:

`Limit: %value.sensor_limit_low / %value.sensor_limit`

**Comment by florianbeer** [comment]
So if I just change the order around it should work?
Will test, thanks!

**Comment by laf** [comment]
I tested it that way and yes it works

**Comment by f0o** [comment]
That template engine is crooked anyways, I dont think it's worth fixing. It's likely easier to get mustache or twig implemented instead.

Pessimistic 2cents

**Comment by laf** [comment]
@florianbeer did this work for you?

**Comment by florianbeer** [comment]
TBH I changed the template but haven't triggered an alert since. Will lower the threshold to see if it parses correctly.

**Comment by florianbeer** [comment]
Works 👍

**Comment by laf** [comment]
We need to document this but thanks for confirming.
