### ISSUE TITLE
Feature Request: Availability Map

### ISSUE THREAD

**Issue by breeman1** [librenms/librenms#4155]
Hi,
I really the new availability map and I appreciate the work put in into making it available.

I would like to propose these two features;
Make the listed devices sort-able by enabling clickable buttons in the top right-hand corner of the screen, I imagine this can be quite useful in getting one to be able to quickly list and zoom into the devices that are currently down as an example.
![snap38](https://cloud.githubusercontent.com/assets/16717388/17837685/a107707e-67b9-11e6-903b-fcc6bae84c15.png)
 The second feature that may prove useful would be the ability to show sysnames/hostnames instead of the ip addresses on the displayed devices.

**Comment by Andreser** [comment]
I second those proposals. 
In my case, I enabled $config['force_ip_to_sysname'] = false; in the config file, because I haven't got dns records for many of my devices, and while I now see device names on my alert list, I still don't see snmp sysname in the availability map. Ideal would be to show snmp-sysname and bracketed [ipaddress] on mouseover, or something like that.

**Comment by crcro** [comment]
@breeman1 @Andreser your requests should be implemented in latest code
