### ISSUE TITLE
Add Device: Cisco Firesight Controller

### ISSUE THREAD

**Issue by PENorris** [librenms/librenms#4524]
Attaching details

http://pastebin.com/TRj1k1Wa

Device is a Cisco Virtual Appliance that controls Sourcefire ASA Inspection Modules.  It was previously owned and developed by Sourcefire and uses snort rules for L7/IDS/IPS inspection.  

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [x] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

**Comment by Rosiak** [comment]
Could you add a snmpwalk from the device?

**Comment by laf** [comment]
I don't see a way to identify these devices from the output you've given us.

They are just generic linux boxes and show the same output as the other issue you created for firePOWER support :(

**Comment by crcro** [comment]
@laf : 

Firesight: Hardware: Generic x86 64-bit Version: 3.10.53**sf.virtual-26** Features:  Serial:

Sourcefire: Hardware: Generic x86 64-bit Version: 2.6.32.24**sf.cisco-28** Features:  Serial:

maybe match those?

**Comment by laf** [comment]
We have one at work which is: 3.10.53sf.virtual-26 #1 SMP Mon Feb 22 20:47:53 UTC 2016 x86_64 but is a FirePOWER as far as I know - which would match FireSIGHT here :( So I'm not 100% sure

**Comment by PENorris** [comment]
FirePOWER is a name for the type of services that it runs.  Cisco loves to change their names for everything around, especially when they buy someone.  AFAIK, the actual appliance is called fireSIGHT.  Specifically in this case, the virtual fireSIGHT manager. 

http://www.cisco.com/c/en/us/products/collateral/security/firesight-management-center/datasheet-c78-732251.html

**Comment by laf** [comment]
I'm still confused, so should we be adding firePOWER and fireSIGHT or just one and if so - which one?

**Comment by laf** [comment]
bump

**Comment by laf** [comment]
No further info provided.

**Comment by Blorpy** [comment]
Alright let me add some clarity here, indicate if more is needed. 

FireSIGHT is no longer used as a term, they are referred to as FirePOWER now.

FirePOWER encompasses a few different things:

FirePOWER Threat Defense Devices (FTD) - Network devices running the newer unified FTD software image. These can include the FirePOWER 2100s, 4100s, 9000s. These are also Linux based, but magically have an ASA image running "inside" them for firewalling functions. In the discovery that I uploaded in #7783 you see a sysDescr of `Cisco FirePOWER Threat Defense, Version 6.2.1 (Build 341), ASA Version 9.8(1)`. Not to confuse people more, but these devices can also run just the normal ASA software image, in which case I am 99% sure that LibreNMS would just see them as a normal ASA. 

FirePOWER services on ASA - A separate Linux "VM" running on an ASA. Not 100% on why you would want to poll this ever. Its a software "module" on the smaller ASAs, it has no physical interfaces. Its a hardware module on the 5585-X ASA, but the interfaces belong to the ASA, not the FirePOWER OS, so you would just poll your ASA management IP and not the FirePOWER one. 

FirePOWER Management Center (FMC) - A Linux based machine (physical, or virtual) that manages the FirePOWER. I poll this with LibreNMS today, and its just recognized as a Linux machine, which is fine because thats all it is, its not passing network traffic, just managing/orchestrating the devices. I think this is what this issue is referencing support for, but as indicated I don't see why having it detected as a Linux machine is a problem.
