### ISSUE TITLE
Physical memory graph

### ISSUE THREAD

**Issue by arjitc** [librenms/librenms#4771]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X ] Please include all of the information between the `====================================` section of `./validate.php`.

LibreNMS Version: 79ac4a687dccdfa729f0e6d424ac129af19d4128
DB Schema: 142
PHP: 5.6.26-0+deb8u1
MySQL: 10.0.27-MariaDB-0+deb8u1
RRDTool: 1.4.8
SNMP: NET-SNMP 5.7.2.1

Would it be possible to display memory split into, Used, Buffers and Cached? rather than 1 graph merging all 3 ?

**Comment by brianara3** [comment]
I would also love to see this feature on the "overview" page for a device. Mainly because all my Linux servers show "physical memory" usage in the 80%+ range but most of it is just cached usage (as it should be). The graphs page has a nice break out of the types of memory usage just fine. 

Another suggestion would be to simply remove the cache/buffer total from the overview graph since those technically aren't "used" memory. Something like the used value when running "free -m"

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-physical-memory-graph/689
