### ISSUE TITLE
Feature Request:  notification integration with slack

### ISSUE THREAD

**Issue by gottaloveit** [librenms/librenms#507]
www.slack.com

**Comment by laf** [comment]
Try this, download: https://raw.githubusercontent.com/laf/librenms/issue-507/includes/alerts/transport.slack.php

into includes/alerts/

Then edit config.php

$config['alert']['transports']['slack']['post'][] = "https://hooks.slack.com/services/AAAA/BBBB/CCCCC"

Change the url to the webhook url that slack gives you.

This needs more work so that you can specify which channel / user the messages are sent to. For now, this will simply send a message to the channel specified in the URL.

@f0o Not sure if I'm along the right path with this. Seems to work ok for me :)

**Comment by gottaloveit** [comment]
Thank you.  This works.

**Comment by f0o** [comment]
:+1:

I wonder if there's a need for multiple slack targets though, might be """nicer""" to strip it down to a `$config['alert']['transports']['slack'] = "https://hooks.slack.com/services/AAAA/BBBB/CCCCC"` format.

But then I've no idea about it, I'd say @gottaloveit could prolly comment on it ;D

**Comment by laf** [comment]
Hey @f0o. You can send alerts then into different channels, it's only like the irc alerter :)

@gottaloveit Any other feedback on this? If not, I'll add it as a new PR to get this into the master branch.

**Comment by gottaloveit** [comment]
I think the multiple notifications is good.   Slack is so channel friendly, that there might be organizations that want notifications in different channels based on user membership in different channels.  I say leave it in.

**Comment by laf** [comment]
Thanks @gottaloveit, we will get this merged into the main base soon.

I'll drop an update here as you will need to revert the changes you've made before updating :)

**Comment by gottaloveit** [comment]
thank you

**Comment by laf** [comment]
@gottaloveit Once the code has been checked, we'd like to merge this in. Technically config options haven't changed but extended, their is some info in the Docs about using this now which you should refer to.

**Comment by laf** [comment]
Closing this now as it's merged in #525
