### ISSUE TITLE
APC Envirnomental  Monitoring

### ISSUE THREAD

**Issue by difi80211g** [librenms/librenms#5140]
Looking for device support on an APC Envirnomental box to report the temperature and humidity inside of LibreNMS.  

Here is the output of the commands:
http://pastebin.com/1Br8n6nP

at the time of testing the temperature was 77 F and the relative humidity was 7%

Thank you in advance

**Comment by Rosiak** [comment]
Any way you can provide access to this device?

**Comment by difi80211g** [comment]
If you can send me a private email with the address you are coming from I could.

**Comment by FTBZ** [comment]
This is for NetBoz series?

**Comment by difi80211g** [comment]
No it is not, Here is a document on it.
http://www.apc.com/salestools/ASTE-6Z5QAY/ASTE-6Z5QAY_R0_EN.pdf

**Comment by Rosiak** [comment]
@difi80211g Which mail address shall send the info to?

**Comment by Rosiak** [comment]
Any news @difi80211g ?

**Comment by difi80211g** [comment]
gmdjunk (it's a gmail address)

**Comment by laf** [comment]
Can you try adding `.1.3.6.1.4.1.318` to the snmpwalk command instead of just `.`

**Comment by axemann** [comment]
I'd like to see support for these devices as well.  

@Rosiak, I can provide access to an [AP9320](http://www.apc.com/salestools/ASTE-6Z5QAX/ASTE-6Z5QAX_R0_EN.pdf) that I have, which is very similar to the AP9319 that @difi80211g has, if needed.

Here's a pastebin of the data @laf was asking for, but for the '9320: [http://pastebin.com/MSui5WT1](http://pastebin.com/MSui5WT1).  The '19 should be similar, but with slightly less output.

I'm actually working on adding support for these on my own system, but I suck at coding, so that banging sound everyone is hearing is me applying face to keyboard repeatedly.  🙁

**Comment by axemann** [comment]
Guys,

I have some additional code I put together for pulling the Sensors and Contacts on my particular unit.  I don't want to mung up the PR that @Rosiak submitted for the initial bits, so I'll wait until after his is approved to see if I need to make any changes.

**Comment by nerdalertdk** [comment]
If you need an test unit I have one I can set up?
