### ISSUE TITLE
Poll device using multiple communities to access contexts

### ISSUE THREAD

**Issue by jlixfeld** [librenms/librenms#5386]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 322bebfd7ae8a872a5c59bd5708d018a2e175951
DB Schema | 153
PHP       | 7.0.8-0ubuntu0.16.04.3
MySQL     | 10.0.28-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

- [x] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.

For my particular use case of this feature, on the Cisco ASR9000 platform, I must use a SNMP context in order to expose routing information that lives within a VRF instance; specifically, BGP neighbour information (i.e.: status, updates, prefixes).  For lack of a better understanding on my part, I believe this ties to CISCO-CONTEXT-MAPPING-MIB, and I think the discussion on more general support for the MIB was by way of [issue 280](https://github.com/librenms/librenms/issues/280).

Currently, the workaround to query information from multiple contexts is for each context-aware device to be duplicated in LibreNMS one time for each context on that device a user wishes to poll.  Each instance of that duplicated device would have it's SNMP Community information populated with whatever context community they wished to have polled.

While it is an effective workaround, it comes with annoying side effects and doesn't scale.  A solution would be to allow LibreNMS to poll multiple communities for a single instance of a device.  This would resolve the scaling issue of the current workaround, and remove the annoying side effects such as having multiple results for a device appear in a global search, duplicate graphs, duplicate information in the database, etc.

I envision the implementation could look something like having two SNMP Community input boxes at https://libre/device/device=#/tab=edit/section=snmp/ where "SNMP Community" could be renamed to "Global SNMP Community" and the additional community input box could be called "Context SNMP Community(s)" which would accept zero or more context communities.

I'm sure other platforms have their own equivalents for CISCO-CONTEXT-MAPPING-MIB, so I guess LibreNMS should be able to figure out which MIB it might need to use depending on what kind of device a context community could be configured on.

While being asked to provide as much detail as possible above, I hope this is adequate detail from someone who is not a coder and doesn't have much of an understanding of what information might be useful to provide to those of you who are :) 

Thanks!

**Comment by DonovanEsterhuizen** [comment]
We have a similar scenario,  nezus 9k with multiple vrf with bgp  neighbors.

**Comment by adaniels21487** [comment]
I hit this a while ago on the Nexus platform. My thoughts on how to attack this are:

1. Configuring the Nexus device.
The device should be configured in a way so that each VRF uses the VRF Name, prepended with the community that is configured for the default context: COMMUNITY-VRF, public in the example below:
Note: Nexus communities have a 32 character limit, entries longer than this will be truncated to 32 characters.

```
     snmp-server context vrf_red vrf vrf_red
     snmp-server community public-vrf_red group network-operator
     snmp-server mib community-map public-vrf_red context vrf_red
     snmp-server context vrf_blue vrf vrf_blue
     snmp-server community public-vrf_blue group network-operator
     snmp-server mib community-map public-vrf_blue context vrf_blue
```

1. A discovery module would then discover a list of VRF's from the default context (CISCO-CONTEXT-MAPPING-MIB - 1.3.6.1.4.1.9.9.468.1.1.1.2) using the device configured community.

1. A poller/discovery module will attempt to extract context specific data by polling the device with the COMMUNITY-VRF format.

**Comment by laf** [comment]
Seems like a logical way to approach it :)

**Comment by jlixfeld** [comment]
Interesting approach @adaniels21487, however I suspect that in some cases forcing a device operator to adhere to a specific community string format would be a breach of some operator's company security policies.

**Comment by adaniels21487** [comment]
Hey @jlixfeld, you may be right. Another thing I though of is: Because of the 32 character limit, if a vrf is 32 characters we effectively have no security as vrfname = community.

What we need is a method of storing device specific configuration variables that are pulled from the database and not dependent on code in config.php. This is what I had in mind in #3002
If we had this, the discovery module could add undefined configuration options when it discovers the vrf. Once set, the discovery and poller modules could their thing on the new SNMP context.

Thoughts?

**Comment by jlixfeld** [comment]
Yeah that's a pickle.  Even if LibreNMS hooks are added to try and discover a device's VRF aware context readiness (i.e.:  by polling a device specific MIB, in my XR case, CISCO-CONTEXT-MAPPING-MIB::cContextMappingTable), you'd still need way to feed it the correct community string, so you're presumably left with a new option in config.php for that context community, aren't you?

In that case, I still like my initial idea; two community text entry boxes :p

**Comment by laf** [comment]
Moved to https://community.librenms.org/t/feature-request-poll-device-using-multiple-communities-to-access-contexts/670
