### ISSUE TITLE
GET http://localhost:8081/js/jquery.cycle2.js.map 404 (Not Found)

### ISSUE THREAD

**Issue by wzhsunn** [librenms/librenms#555]
Is this a problem ?

**Comment by laf** [comment]
Shouldn't be, it only does it when you have developer tools in your browser open iirc.

**Comment by wzhsunn** [comment]
My local Librenms system can run as usual with the problem mentioned above. Besides, I also find this problem occurs at the official online demo website 'http://demo.librenms.org/'.------GET http://demo.librenms.org/js/jquery.cycle2.js.map 404 (Not Found)

**Comment by laf** [comment]
I'm 100% sure this is because you are browsing the site with developer tools enabled:

http://stackoverflow.com/questions/18365315/jquerys-jquery-1-10-2-min-map-is-triggering-a-404-not-found

we can (and probably should anyway) add the source map although I can't find one for this version of cycle2 we are running. Two options are upgrade cycle2 (from github) or remove the map reference in the minified file for cycle2.

**Comment by wzhsunn** [comment]
You are right , I follow the stackoverflow method  and change my developer tools setting, it dose not show the error any more .
