### ISSUE TITLE
Proxmox application cleanup

### ISSUE THREAD

**Issue by tsumaru720** [librenms/librenms#5786]
Hi All

Not sure if this counts as a bug or feature request :)

If I have a vm in Proxmox that has for example VMID 150 - This will be auto-discovered/added when the "application" poll completes. 

If this VM is then removed from the cluster and no replacement VM is created with said VMID, then the old device lingers around in the web interface. Would be nice if you could auto remove this if its not returned on poll (although might pose a problem if the VM moves host though) , or under daily cleanup if not seen for x number of hours (last seen is logged in the DB under librenms.proxmox -> last_seen and similarly under librenms.proxmox_ports)

Component | Version
--------- | -------
LibreNMS  | 389cf5414cf6c0afb904a97581d32d595724f363
DB Schema | 159
PHP       | 5.5.9-1ubuntu4.20
MySQL     | 5.5.53-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2

**Comment by svennd** [comment]
I think its difficult to adapt/change, as long as the RRD file for the VM is there the graph will be drawn. It cannot be removed since the VM might be temporary down during polling... I don't think its a good idea to remove the RRD automatically. Similar behavior is seen for all applications I believe, I tested the mysql server app once, and now its in my interface for ever until I remove the rrd.

So I believe its more a feature ?

**Comment by laf** [comment]
Moved to #6807
