### ISSUE TITLE
ifSpeed missing on device that doesn't have ifHighSpeed

### ISSUE THREAD

**Issue by murrant** [librenms/librenms#6257]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

./poller.php -h HOSTNAME t -m ports -d
https://p.libren.ms/view/0cc810bf

snmpwalk:
https://p.libren.ms/view/c9f4ee69

**Comment by laf** [comment]
We could add ifSpeed to be obtained as well, it would marginally increase poll times.

Someone else has reported an issue which because the first index is missing for ifHCInOctets then we skip to non-hc. Things like this and that strike me as where we should say please speak to the vendor to resolve this - surely if you return data for ifXEntry you should return it all.

An alternative would be a more intelligent system that overtime works out what stats a device has and we start to only poll for that.

**Comment by murrant** [comment]
Learning poller, interesting idea.  Yeah, boo for broken snmp, but that is our reality.
