### ISSUE TITLE
New Device Support - Cyan Z33

### ISSUE THREAD

**Issue by vladutz33** [librenms/librenms#6337]
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
Component | Version
--------- | -------
LibreNMS  | a0abcbb6496def0bacc77fb811064c314c6d087e
DB Schema | 184
PHP       | 5.5.9-1ubuntu4.21
MySQL     | 5.5.54-0ubuntu0.14.04.1
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.7.2

Device: Cyan Z33

Device Homepage: http://media.ciena.com/documents/Z33-Packet-Optical-Platform-DS.pdf

Device MIBs:
https://app.box.com/s/n8qenrdr71etf23mx4j5yje0rx5jou1q

SNMP:
https://pastebin.com/vSRy6EX1

Discovery
https://p.libren.ms/view/348232a9

Poller
https://p.libren.ms/view/e8783f7a

**Comment by murrant** [comment]
This snmpwalk seems to only contain basic information, did you use the command in the faq?

`snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh`

The dot at the end is important.

**Comment by vladutz33** [comment]
This command timed out snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME . | ./pbin.sh , and I used this command instead snmpwalk -OUneb -v2c -c COMMUNITY HOSTNAME . >> cyan_z33 and uploaded the output to pastebin but I think I missed the dot at the end. I ran the command again and reuploaded the file here https://pastebin.com/vSRy6EX1

**Comment by laf** [comment]
Have you removed things sysDescr values? We do need that info, if it contains sensitive info please mask it out rather than removing it. Once you've provided the info we need we can re-open this.

**Comment by vladutz33** [comment]
I didn't remove anything , not even the sensitive data. Do you need me to run a different snmpwalk on this device?

**Comment by esorin0** [comment]
I see this .1.3.6.1.2.1.1.1.0 = STRING: "Z33" in the last pastebin file. Isn't that OID for sysDescr?

**Comment by laf** [comment]
These are already detected. If you have specific requirements then you need to specify what those are.

**Comment by esorin0** [comment]
I'd like to see: traffic and errors on 10G and 1G ports (there is an 100G card, but we don't have it and we cannot provide any SNMP output for that), light levels, where they are available (they do not seem to report it for all ports). Thank you!

**Comment by laf** [comment]
I'm confused, you're asking for things that either you can't provide data for or the device doesn't provide. How are we supposed to do that?

**Comment by esorin0** [comment]
I am not able to provide 100G data, I was just mentioning that, in some
configurations, device has 100Gbps ports.
As far as light levels, SNMP engine does not provide them for all the
interfaces. I know it does for 10G interfaces, even if their proprietary
management software shows light levels for all ports, no matter the speed.

Thank you!

**Comment by laf** [comment]
Please provide the OIDs needed.

Also, please in future provide what info you want to see when asking for support.

**Comment by esorin0** [comment]
I know you are not a mind reader, but this is a networking device. Any
basic implementation for such a device (doesn't matter the vendor) should
include at least traffic and errors for all the ports that are available.
That's why we did not make any specific requests. Light levels, I agree,
they would be something I would specifically ask for.

As far as providing OIDs seems to be weird, since that info is provided in
MIBs. If I provide you my OIDs, those won't necessarily be enough for other
people, since I do not have every single port on the device up nor all the
possible cards available. And what is happening when I turn on a new port:
ask you again for a feature request to add one more OID? This does not
scale for a device that can have over 100 ports  and such a large variation
of possible configurations (it is card based and there are available more
than 7 different cards).
Thank you!

**Comment by laf** [comment]
Ports have a well defined mib called IF-MIb if a vendor chooses not to use it then fine but people can't expect us to check every request looking for standard port info through and entire snmpwalk or mib. 

Provide where the info is and support can be added.

**Comment by laf** [comment]
I was on my phone earlier.

We don't need every OID in the world to add support, interfaces will be in one table most likely regardless of speed. However they should be in IF-MIB, some vendors stupidly choose to ignore this universal standard and push data through another MIB which is fine and we can add support.

The issue is, you've asked to add support but seem to be assuming that we'll go through the entire output and mib to find every scrap of data we can and add support. This isn't a paid for product and we expect users to provide the information or at least  details on what you'd like to see, if you tell me the OID or name of the table to lookup I'll do the rest but I'm not spending my time to find it.

**Comment by laf** [comment]
p.s You even confirmed in the check box 'Please provide as much detail as possible.' but provided nothing other than the walks / debug info we ask for in the point above.

**Comment by esorin0** [comment]
Neil,

You are right. I will research and provide you the table info.
Sorry for the inconveniences our request might have caused. We've read your
documents prior adding request, but some devices are a lot more complex
than others and there are situations one cannot foresee. This particular
device is a pain for us too, not only from SNMP point of view.
Also, I would like to keep discussion at a professional level and stay away
from Observium-like attitude and responses.

Thank you for your help!

**Comment by murrant** [comment]
No problem Soren.

We just need your help as we are not familiar with the hardware.  Highlighting specific mib entries you would like collected is especially helpful.  Anything you can do to to help us out is appreciated.
