### ISSUE TITLE
Less restrictive Contributor License Agreement possible?

### ISSUE THREAD

**Issue by gs-kamnas** [librenms/librenms#8341]
We are currently using LibreNMS and have developed several expansions for such including bugfixes, adding support for additional devices, as well as additional metrics reporting extensions that we would like to contribute back to the LibreNMS Open Source project. However, we are facing difficulty securing the approvals needed to contribute code on behalf of our firm as a result of the following clause in your CLA: 

                "You are not running a copy of non-GPLed Observium, whether as part of your work duties, or personally, or in any other capacity, and you have removed any copies of non-GPLed Observium source code from your personal and work systems."
                
Us as the team developing and supporting LibreNMS has had absolutely no interaction with Observium in any way, and will not view the non GPL Observium code or take any influence/ideas from such during our development for LibreNMS. However, since we are a global firm of over 34,000 employees, we would not be able to conclusively prove that _nobody_ else internally is running or viewing non-GPL Observium code. As a result, there is concern regarding being able to honestly agree to the final statement of your CLA. However, such statement on your CLA is unusually restrictive compared to nearly all other open source projects. For example, this would be similar to saying that because you or your company uses or holds a copy of the Microsoft Windows SDK (which is under a nonfree license), that you may not contribute to the Linux Kernel (GPLv2), even if you do not use any code, processes or ideas from the Windows SDK in your contributions to the Linux Kernel.

Therefore with this said, **would it be possible for the last clause of your CLA to be revised or omitted, since it will be very difficult or impossible for us to contribute to your project otherwise.**

Regards,
Nash Kaminski & Garry Shtern
Goldman Sachs & Co.

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by laf** [comment]
I'm away at a conference until late Friday so might not be able to respond until the weekend in more detail.

However, one thing that might help us here is if you can give us an idea of what areas of the code base you're talking about. For new devices done in yaml and code that's most likely similar to what's there then it's not an issue as that's all been done by us since the fork. Same with lots of the code base in general.

So the short answer is, we can probably work something out if you can give us an idea which areas of the code you've touched.

**Comment by murrant** [comment]
It is overly restrictive because we have had legal threats and DMCA takedowns from the original authors. (Not in a long time)

Luckily, it becomes less of an issue as the code bases diverge as it is more and more difficult to steal code from Observium and add to LibreNMS.  We have to protect the project from individuals doing this.

I think there could be a way to relax the wording, but we are not lawyers.

If anyone has some better wording, we would review it.

**Comment by garryshtern** [comment]
Some of the modifications we have made involve device  models, polling and API.  As we start using more and more features, we would like to contribute whatever changes we implement to make it more usable.

As such, listing particular parts of the code that we intend to modify is a bit difficult right now, since it is bound to change over time.

Can you enumerate specific parts of the code that might be in conflict at this point, instead?  Perhaps, CLA can be adjusted to include just those, instead of the entire code base?

**Comment by laf** [comment]
So saying which parts might be in conflict is hard right now as we'd have to kind of audit the code in more detail.

We are safe to say though the following sections should be fine:

API
Alerting system
Any yaml file for discovery
Test units
Code for InfluxDB, Graphite and OpenTSDB
Device groups
Dashboard
Oxidized
Graylog support
FDB Search
Geolocation
PeeringDB
Distributed polling
WebUI Settings

A lot of the other code has also been refactored in smaller chunks so it's possible it's no longer original code.

We are trying to get a lawyer to review the CLA to see. However if you like, you can submit your pull request without signing the CLA and we could give you our opinion on it and potentially see what we can do?

**Comment by theherodied** [comment]
Honestly I feel that the prior clause covers it and the latter is redundant and unnecessary. 

A company could legally run both products or have access too them as long as they don't copy code from one to the other.

**Comment by theherodied** [comment]
Additionaly, I feel the last clause is easily worked around by simplying having the code on a removable medium or having it online, thus rendering the clause useless. 

Either way the prior clause covers your liability by having the contributer agree they are acting in good faith. 

Below is the current cla for reference. 

Contributor Agreement
By contributing code to LibreNMS (whether by a GitHub pull request, or by any other means), you assert that:

You have the rights to include the code, either as its original author, or due to it being released to you under a compatible license.

You are not aware of any third party claims on the code, including copyright, patent, trademark, or any other legal claim.

You have acknowledged in the content of your contribution (usually as a source code comment) any and all sources and influences used in the production of that contribution.

You have not viewed code written under the Observium License in the production of contributed code. This includes all Observium code after Subversion revision 3250 and any patches or other code covered by that license after Tue May 29 13:08:01 2012 +0000 (the date of Observium r3250).

You are not running a copy of non-GPLed Observium, whether as part of your work duties, or personally, or in any other capacity, and you have removed any copies of non-GPLed Observium source code from your personal and work systems.

**Comment by laf** [comment]
@gs-kamnas Any response from your side in regards to our questions? We'd love to get you in a position where you can submit a pull request.

**Comment by laf** [comment]
@murrant / @theherodied So shall we get rid of:

```
You are not running a copy of non-GPLed Observium, whether as part of your work duties, or personally, or in any other capacity, and you have removed any copies of non-GPLed Observium source code from your personal and work systems.
```

**Comment by theherodied** [comment]
@laf, I say remove it!

**Comment by laf** [comment]
@murrant Any comment before I make this change? Are you in agreement we should do this as well.

**Comment by murrant** [comment]
I agree it seems ok to remove that line.  The previous should cover us.

**Comment by murrant** [comment]
@gs-kamnas CLA updated.  Thanks and send your changes :-)

**Comment by garryshtern** [comment]
Appreciate the change. We are preparing the changes, and will be submitting them upstream very soon.
