### ISSUE TITLE
Improvement: RANCID integration

### ISSUE THREAD

**Issue by SaaldjorMike** [librenms/librenms#852]
Would be nice if one could look through old versions of the configurations - and not only the most recent. The config is already in rancid so should be possible. Previously I've been using rancid-git with a gitweb frontend, but would be even more nice with the configurations from within LibreNMS.

**Comment by supertylerc** [comment]
This would require a bit of work, I think.  We would need to detect the VCS being used (cvs, svn, or git) and provide support for all three in a single, fluent interface.  It's not impossible, but it is a decent bit of work to incorporate.  Perhaps adding incremental support for one VCS at a time would be prudent.  I suspect that git would be last, though, as it is fairly new to the RANCID scene.

**Comment by f0o** [comment]
We have Oxidizer support now as of ddc1d05262fb8de1280311bb7b6c5488d9da74c2, Does this make RANCID redundant/obsolete?

**Comment by laf** [comment]
I'd say we possibly need to support RANCID still as well.

**Comment by paulgear** [comment]
I definitely wouldn't want to throw out RANCID support.

**Comment by killsudo** [comment]
I would vote for rancid-git first up and basic config views if possible. The main reason I say rancid-git is because it's easy to integrate with GitLab to generate colorized email diffs on commit AND already ties into AD/LDAP for sso between librenms and gitlab in a group/team environment.

**Comment by killsudo** [comment]
Another nice aspect of Rancid-Git and Gitlab is the ability to restore device configs securely.

All of our spare devices are programmed into dhcp and dns.

LibreNMS adds the required info to Rancid to begin backing up the device. Because git is used the commits are replicated to Gitlab and it's awesome user / group security. NOC team is able to review the configs in depth via GitLab or LibreNMS based upon which access or rights they are granted.

The failed device is unracked, and the backup device is racked.

Upon power on the backup device grabs it's assigned ip via dhcp.

Because we already programmed the device into dns we have a hostname to work with.

We launch a script from the NOC using the backup device hostname and the hostname of the failed device.

The script fetches the backup config directly from the GitLab git repo using the device hostname (instead of hitting librenms directly), does what it needs with the configuration to make it ready for pushing.

The script then uses the backup device hostname to access the replacement, push the configuration, and saves or reloads the device as necessary.

Alot of times rancid itself can be used to restore the device config easily but for certain devices you will need a script to help out with a few other actions.

We avoid hitting the files on LibreNMS for two reasons. The script will use an https call to fetch the file securely with an API token from GitLab and allow us to limit access to sensitive information.

**Comment by killsudo** [comment]
I've also been toying with the idea of putting the rancid config itself in git. If LibreNMS could generate the rancid files locally to a directory that's checked into git then the files could be pushed to GitLab on each commit and colorized email diffs generated for device/group add/removes as LibreNMS runs.

Then on our rancid box we could use git to pull the new rancid configs down into the rancid box before rancid runs across the groups/devices.

Why? Cause if your storing the ipsec/ssh/bgp session keys etc to your entire network, not letting that info be exposed via a web application can be critical. Yes I can't view the configs in LibreNMS with this design for security but I can via GitLab if I have the proper permissions assigned.

A device config with sanitized passwords/keys/ipsec etc is useless during a failure scenario where you want to quickly restore services in a semi-automated fashion.

**Comment by buraglio** [comment]
Is this RANCID support working? I can't seem to figure out how it is supposed to display and the docs seem a little sparse (or perhaps I am just tired and not seeing them). Loving this as an NMS too, BTW. I'd not looked at it in some time.

**Comment by paulgear** [comment]
@buraglio LibreNMS needs to be pointed at each configs directory inside your RANCID install, so if you're collecting RANCID configs in /var/local/rancid and you have groups dev, test, and prod defined, then you need to set up LibreNMS like this:
```php
$config['rancid_configs'][] = '/var/local/rancid/dev/configs/';
$config['rancid_configs'][] = '/var/local/rancid/test/configs/';
$config['rancid_configs'][] = '/var/local/rancid/prod/configs/';
```

**Comment by paulgear** [comment]
@buraglio After that you should see a config tab in each device screen.  The names must match exactly the files in there, so if you're using FQDN in one and shortname in the other, it won't work.

**Comment by buraglio** [comment]
Thanks for the help, @paulgear. For the ones I was testing it was a simple permissions issue. After adding the correct users to the correct groups they started working. I still need to make it work with some of the others but it's demonstrably functional on my system now.  Thanks for the great work!

**Comment by papringle** [comment]
@buraglio I'm having similar permissions issues with librenms and rancid.  Would you mind sharing what files/directories needed changed and what the user/group names need to be assigned?  Thank you!

**Comment by laf** [comment]
@papringle I expect you just need the web server to have permissions to access the files.

**Comment by buraglio** [comment]
Yup, that was it. I am usingf Ubuntu so I just has to add the web server user (www-data) into the rancid group and then verify group rancid had read access. Simple fixes are always my favorite.
