### ISSUE TITLE
Event log entries for ifSpeed and ifHighSpeed

### ISSUE THREAD

**Issue by SaaldjorMike** [librenms/librenms#880]
Currently both ifSpeed and ifHighSpeed is shown in the eventlog. While this is not wrong to do, it seems kinda redundant.

**Comment by Rosiak** [comment]
Agree with Mike here.

**Comment by f0o** [comment]
although I generally agree with you, I would like to point out that the eventlog is (from my pov) a sort of verbose/debug log about the device in question.

I assume (without having looked at code) that it may be two separate operations that determine ifSpeed and ifHighSpeed. If so, each entry for itself has a legitimation to exist as they determine different datasources.

I do understand that these kind of messages are very redundant, same as the 3-4 events for ifDown-actions..

However, I'm afraid we shouldnt scrap these entries because of aesthetic reasons as they may become relevant for debugging purposes.

**Comment by laf** [comment]
I'd agree with @f0o on this one.

Doesn't mean we can't look at a way to better display this information in the webui though.

**Comment by SaaldjorMike** [comment]
@f0o does make a good argument. Lets us close this for now.

**Comment by YukonRob** [comment]
Sorry to resurrect this. How can I stop logging of this info altogether? I have auto negotiating microwave links filling my event log with ifSpeed entries.
