### ISSUE TITLE
Enabling client count on a Ruckus standalone AP

### ISSUE THREAD

**Issue by ZummiGummi** [librenms/librenms#8859]
- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Discovery - https://p.libren.ms/view/580221d7
Poller - https://p.libren.ms/view/ea9b3127
SNMPBulkWalk - https://p.libren.ms/view/7e92debc

I have a Ruckus R510 access point added to LibreNMS. I noticed that the count for the number of clients is blank. I was able to get these value through PRTG using the follow OID's (works for various other models like R600, R610, R300, TS301S).
1.3.6.1.4.1.25053.1.1.12.1.1.1.3.1.3.1 for 2.4 Ghz clients.
1.3.6.1.4.1.25053.1.1.12.1.1.1.3.1.3.2 for 5Ghz clients. 

These values were found in MIB **RUCKUS-RADIO-MIB**, ruckus radio stats, ruckus radio stats num auth sta

My LibreNMS version is **1.40-37-g357139b - Thu Jun 28 2018 03:10:39 GMT+1200**

Would it be possible to get this working. My apologies if this is a bug in my installation.

**Comment by BeresfordHare** [comment]
[RUCKUS-RADIO-MIB.txt](https://github.com/librenms/librenms/files/2153792/RUCKUS-RADIO-MIB.txt)
Attached is the MIB.

**Comment by utelisysadmin** [comment]
Hi. I am also looking into grabbing these value among others. These work fine when querying a ZoneDirector Controller, but fail for me when using a SmartZone Controller or querying directly the access point. I've gotten all the MIB files from Ruckus and will try to develop something when I have the time. 

P.S. - I think the MIBs are slightly different. I am also having problems with "Unleasehed" APs, where Ruckus saw fit to disable SNMP on "child" APs.

**Comment by BeresfordHare** [comment]
My setup is a Virtual SmartZone (Essentials), controller version 3.6.1.0.227 with AP firmware version 3.6.1.0.354.
The access point is queried directly, since I don't think the controller will return this information.

**Comment by BeresfordHare** [comment]
[RUCKUS-ROOT-MIB.txt](https://github.com/librenms/librenms/files/2161102/RUCKUS-ROOT-MIB.txt)
[RUCKUS-SZ-CONFIG-WLAN-MIB.txt](https://github.com/librenms/librenms/files/2161103/RUCKUS-SZ-CONFIG-WLAN-MIB.txt)
[RUCKUS-SZ-EVENT-MIB.txt](https://github.com/librenms/librenms/files/2161104/RUCKUS-SZ-EVENT-MIB.txt)
[RUCKUS-SZ-SYSTEM-MIB.txt](https://github.com/librenms/librenms/files/2161105/RUCKUS-SZ-SYSTEM-MIB.txt)
[RUCKUS-SZ-WLAN-MIB.txt](https://github.com/librenms/librenms/files/2161106/RUCKUS-SZ-WLAN-MIB.txt)
[RUCKUS-TC-MIB.txt](https://github.com/librenms/librenms/files/2161107/RUCKUS-TC-MIB.txt)
[RUCKUS-CTRL-MIB.txt](https://github.com/librenms/librenms/files/2161108/RUCKUS-CTRL-MIB.txt)
[RUCKUS-PRODUCTS-MIB.txt](https://github.com/librenms/librenms/files/2161109/RUCKUS-PRODUCTS-MIB.txt)
Attached are the MIBS for the Ruckus SmartZone controller.
These do provide information about the access points, and is probably a better way of getting this information instead of polling the AP directly like I am currently doing.

Should this issue be closed and a new one created for adding a SmartZone controller instead?

**Comment by utelisysadmin** [comment]
So I've hit a snag. I've fixed the SmartZone AP and Clients situation, however I don't have the MIBs for queering the APs directly. They do provide a lot of info, however without the MIB, I don't know what is what. The only thing I've found is a document called "SNMP Reference Guide" for access points. There are no MIBs however.

**Comment by utelisysadmin** [comment]
The information available on the Controller is also not that much. I am missing a lot of thing that are available on the SZ dashboard. So either:
a) SZ asks the AP for this info via SNMP
b) SZ asks the AP for this info via the propriatary Ruckus internal API.

Hopefully it's not option B.

**Comment by BeresfordHare** [comment]
[Ruckus_MIBs_100.1.0.0.432.zip](https://github.com/librenms/librenms/files/2174083/Ruckus_MIBs_100.1.0.0.432.zip)
Here are the latest MIBs I could find for standalone AP's. Hopefully this helps a bit.

**Comment by utelisysadmin** [comment]
It does. I eventually found some, but they were version 9.6. Thanks. This is newer. Just need to figure out how to do the logic now, because we have the following:
- ZoneDirector Family with respective WLC and AP software
- SmartZone Family with WLC and AP software
- Unleashed Family where only the "activing" WLC is monitorable.

Furthermore there is also their consumer brand(XClaim) which is a trimmed down version of the enterprise family. I have these as well.

**Comment by djamp42** [comment]
@utelisysadmin Has anyone done any work on this?  I was going to start looking into it. I have access to all 3 types of devices, so my thought was to break out the 3 devices into there own OS, (I'm assuming they all use different MIBs for client count/etc).

**Comment by utelisysadmin** [comment]
Hi, I've actually already implemented it. Did not have time to open a PR.

I am monitoring the following devices: SmartZone controller, SmartZone AP, ZoneFlex Controller, ZoneFlex AP, Ruckus Unleashed AP(only primary one has working SNMP).

It's monitoring "number of clients", "number of APs" and "utilization", "model", "serial" etc.

**Comment by djamp42** [comment]
nice that's awesome, are you planning to? I wouldn't mind testing it out with all my ruckus stuff.

**Comment by xciter327** [comment]
Here. This is all I've got so far:

https://github.com/librenms/librenms/pull/9684

**Comment by djamp42** [comment]
Do you have the PHP files for polling the wireless client count/ os discovery? I just tried it on mine, but these are missing.

**Comment by xciter327** [comment]
Forgot to add them to the PR. I've added them to my fork in "/opt/librenms/includes/polling/os". Tomorrow I'll figure out how to add them to the PR.

**Comment by djamp42** [comment]
No problem, i tried your ruckuswireless-sz.inc.php but it failed to find most of the fields (SN/Model/Hardware). I did change it around, and now it properly discovers on mine, just want to make sure it works on yours. I don't know if something is changing between firmware versions, i'm on 3.6.2.0.78

[ruckuswireless-sz.inc.php](https://raw.githubusercontent.com/djamp42/librenms/ruckuswireless-rework/includes/polling/os/ruckuswireless-sz.inc.php)

**Comment by xciter327** [comment]
I'm running SZ-104 with 3.6.1.0.227 and the discovery works. It works with your php file as well tough. Do You have other kit we can try the rest with?

**Comment by djamp42** [comment]
I think yours was just too specific with the OID, it seems like some of them are randomly generated after a certain point.  Both of my sz are on the same firmware, so i don't have another one. i still need to test the zd/aps/unleashed. I'll just create another branch based on yours and we can see how each one works.

**Comment by djamp42** [comment]
also do you have the client/ap polling files? Should be in librenms/LibreNMS/OS/

**Comment by xciter327** [comment]
It's possible. I remember having issues making LibreNMS differentiate between the different OS's so I needed to be very specific. I've tried Your changes and so far it works great between ZD/SZ/Unleashed/APs. 

PS - I've added the requested files to my fork.

**Comment by djamp42** [comment]
i've made a lot of progress on this, basically some of your OIDs were too specific. Also ZD1200 and Unleashed AP's actually use the same sysObjectID, so that's a pain to deal with.. I think i have that figured out and mostly everything working now, just need to clean up the code a bit and maybe add cpu/memory/temp. should have something next week.
