### ISSUE TITLE
New device: iBoot PDU

### ISSUE THREAD

**Issue by JacksonB** [librenms/librenms#9287]
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Adding this to LibreNMS identifies it as a server. The type should be Power.
sysName on multiple devices is always returning `ibootpdu`. The OID for determining that should be `.1.3.6.1.4.1.1418.6.1.2`

Discovery: https://p.libren.ms/view/04952837
Poller: https://p.libren.ms/view/386d6831
SNMP: https://p.libren.ms/view/4072676a

Vendor MIB: [iboot-pdu.mib.zip](https://github.com/librenms/librenms/files/2443817/iboot-pdu.mib.zip)

Please let me know if I can provide further information.

**Comment by PipoCanaja** [comment]
Hi,

Just a short point : if sysName does not reflect the actual hostname, there is no way to properly override this today in the current discovery and polling model in LibreNMS. 
I would suggest to check with provider if there is another solution for this (improving the device microcode for instance). 
I had this issue on a OOB management for a server (Huawei) and until the fix is released, the workaround is simply to snmpwrite a new sysname to the device. This actually works, and is even saved between reloads. The fix is currently being developped and should arrive early 2019. 

Bye
PipoCanaja

**Comment by PipoCanaja** [comment]
HI @JacksonB 
You can test the PR #10898  for added support. 
Bye
