### ISSUE TITLE
Device group patterns are truncated at 255 chars

### ISSUE THREAD

**Issue by TrevorPH** [librenms/librenms#935]
Setting up device groups and I found that if a pattern exceeds 255 chars then it is silently truncated in mid-pattern causing syntax errors. I've run alter table device_groups modify column pattern varchar(4096) not null; and this sets it to a larger length before the problem would be hit. It'll still truncate at 4096 but I'm unliklely to hit that for a while.

**Comment by f0o** [comment]
We cant change it to >255 because of backwards compatibility with MySQL <5.3.0
However we can change it from `VARCHAR` to `TEXT`.

I still wonder how you hit 255 characters for a group-definition.
Maybe there could be done some optimization to your patterns..

I'll PR a field-change from `VARCHAR` to `TEXT` shortly
