### ISSUE TITLE
Total Traffic Legend Alignment is off

### ISSUE THREAD

**Issue by mrjester888** [librenms/librenms#951]
The "out" lines are not lined up with the "in" lines in the legend.  This is sourced from the Total Traffic page, but may be impacting elsewhere.

![image](https://cloud.githubusercontent.com/assets/5603366/7551389/21a56048-f63b-11e4-964e-971ba7ea6b9e.png)

**Comment by laf** [comment]
Ok this is due to:

function rrdtool_escape($string, $maxlength = NULL)

What happens (for me at least) is that on my graphs where this happens (as it doesn't happen on all) is they have : in the name so these are escaped to /:. This happens twice within one name, when the str_pad is done it uses a strlen check against the before and after escaped value so in my case we end up with a difference of 2 (due to the two extra /). However the second one would be after the maxlength, so the actual maxlength is then 12 for the out interface (i.e displays 12 characters) yet in is always 10.

I expect something similar is happening above except the opposite (not sure why you don't have interface labels).

Needs sometime to play around with that function.

In the meantime, can you confirm what device this is as I've never seen no interface descriptions in a graph before.

**Comment by mrjester888** [comment]
Hardware: cisco1811
Operating System: Cisco IOS 12.4(24)T2 (ADVIPSERVICESK9)

**Comment by laf** [comment]
Should all be sorted now @mrjester888
