### ISSUE TITLE
New OS Request - Pakedge

### ISSUE THREAD

**Issue by tuksaur** [librenms/librenms#9693]
a while back i was looking into this but never followed up on a previous ticket (ref #4108). had the time to sit down and re-add a few Pakedge devices and was hoping adding support for the hardware would be possible. Below are the discovery, poller, and snmpbulkwalk of the device.

**./discovery.php -h HOSTNAME -d -m os**
https://p.libren.ms/view/ada313dd

**./poller.php -h HOSTNAME -r -f -d -m os**
https://p.libren.ms/view/4ef0b44e

**snmpbulkwalk -On -v2c -c COMMUNITY HOSTNAME .**
https://p.libren.ms/view/a0232fc7

vendor site:
https://www.pakedge.com/

we use mostly their switches and WAPs in our environments but very little documentation out there on the back end of their hardware as they are a "pro-sumer" product for home automation. starting to move away from them but would like ability to at least monitor network graphs more accurately. currently they come in incomplete, missing large chunks of data

![pakedge-libre](https://user-images.githubusercontent.com/17806002/51363749-7f5a5d80-1aa7-11e9-811c-16706195ee5d.PNG)
.

**Comment by murrant** [comment]
I have bad news for you, LibreNMS can't fix the gaps.  Maybe you can: https://docs.librenms.org/Support/FAQ/#why-do-i-see-gaps-in-my-graphs

Can probably add better detection for the OS however.

**Comment by tuksaur** [comment]
thank you @murrant i have several pollers all of which complete their polls in under 300 seconds. 

![pollers](https://user-images.githubusercontent.com/17806002/51394814-4e127980-1b09-11e9-941b-7b8a24797b02.PNG)

![bh-pollers](https://user-images.githubusercontent.com/17806002/51395052-dabd3780-1b09-11e9-8ef0-dccf97ade790.PNG)

i have an dedicated rrdcache running already so down to DNS optimization. I will try pdns-recursor to see if that helps. we run dmvpn to many 'remote' locations so may require a local poller to this site to test. 

in my experience it has always been an issue even with local poller and using IP resolution instead of DNS. perhaps improved OS detection could help as well. unfortunately manufacturer has no MIBs available or SNMP monitoring support.

**Comment by PipoCanaja** [comment]
@tuksaur 
Improving the detection will definitly improve the display with a logo etc etc but will also put more load into the snmp polling (because polling more OID takes more time and has more chances to fail over a dmvpn link. 
Try to play with the different timer values in order to improve your current results with standard MIB. 

Concerning the detection, the basic discovery and standard sensors usually does not involve any coding at all and can be done quite easily. 
https://docs.librenms.org/Developing/os/Initial-Detection/
https://docs.librenms.org/Developing/os/Health-Information/
You can start to play with these in your Environnement, and come up with a pull request to continue discussion or contact us on discord to get help on how to do it. 
Bye

**Comment by murrant** [comment]
This issue has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-os-request-pakedge/11633/1

**Comment by Jellyfrog** [comment]
This request has been moved to: https://community.librenms.org/t/11633
